### ISSUE TITLE
It don't seems to work in iTerm2

### ISSUE THREAD

**Issue by Jim-Zenn** [joshdick/onedark.vim#1]
I installed the scheme with iTerm2 and MacVim. In GVim it works well. However, it don't work in iTerm2 as it should.
Here's the relevant code in ~/.vimrc
```
" Basics
set nocompatible " get out of horrible vi-compatible mode [Vundle required]
filetype off " [Vundle required]
set encoding=utf-8

" Font
set guifont=PragmataPro\ for\ Powerline:h16

" Scheme
syntax on " syntax highlighting on
set t_Co=256
set background=dark
colorscheme onedark
let g:onedark_termcolors=256
let g:onedark_terminal_italics=1

```

**Comment by joshdick** [comment]
What happens if you omit the `set t_Co=256` line?

All of the `g:onedark` variable declarations need to appear before the `colorscheme onedark` line for them to have any effect.

You also shouldn't need to set `g:onedark_termcolors` at all, since 256 is the default.

**Comment by Jim-Zenn** [comment]
Thanks for your help.

I tried everything I can. It just don't work. Don't work in both Mac Terminal and iterm2. Don't work with MacVim or NeoVim. It only works in MacVim GUI.

Not only this color schemes, none of the color schemes except solarized works the exact way as the preview pics. There are always an apparent difference. Even those Base 16 schemes do not work correctly.

My iterm2 is set to xterm-256. Any idea how this happens?

**Comment by Jim-Zenn** [comment]
Oh... Finally I got the solution!
neoVim has an option:
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
and it solves everything.

Though I don't know what this is but it's great!

Thanks anyway :P

**Comment by joshdick** [comment]
Glad you figured it out!

**Comment by shangsunset** [comment]
Hey Josh! 
I installed One Dark.itermcolors, and set the theme to use terminal's color. bui i still cant get the color right.
![screen shot 2016-02-01 at 10 18 50 am](https://cloud.githubusercontent.com/assets/3700269/12721314/36c5e7d0-c8cd-11e5-8c6b-3679992dde27.png)

my config:
```
syntax enable 
let g:onedark_termcolors=16
colorscheme onedark
set background=dark
```

any idea where i did wrong? thanks.

@Jim-Zenn I also tried `let $NVIM_TUI_ENABLE_TRUE_COLOR=1` as im using neovim, but it didnt work for me. can i see your config file regarding to the theme if possible?

**Comment by Jim-Zenn** [comment]
I think if your config file is right. Make sure you add the line if you are using nvim. You may want to check your terminal setting. What terminal are you using? iTerm2?

**Comment by joshdick** [comment]
The colors themselves look correct, but if you're wondering why the highlighting doesn't look exactly like it does in my screenshot, it's because I'm using the [othree/yajs.vim](https://github.com/othree/yajs.vim) plugin which has better JavaScript highlighting than stock Vim.

**Comment by shangsunset** [comment]
got it. thanks for the help guys!

**Comment by filipebarros** [comment]
I had to remove the `set background=dark` for the theme to work. Without it it looks fine
