### ISSUE TITLE
Highlighted text has the same background colour as default text

### ISSUE THREAD

**Issue by locknic** [joshdick/onedark.vim#104]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

Terminal emulator(s) and their version(s) used, if applicable: `iTerm2 3.0.15`

### Issue Description

Not sure if it is intended to be like this, but the select (e.g. highlighting for copy/paste) appear to have the same colour text and background as the default text.

![screen shot 2017-06-01 at 12 51 52 pm](https://cloud.githubusercontent.com/assets/1709110/26698259/1b4bccbe-46ca-11e7-9737-6582a5f050e7.png)

**Comment by joshdick** [comment]
No, this was not intended, nice catch!

Fixed in d94b5df.
