### ISSUE TITLE
Diff lines being extremely hard to see with cursorline on

### ISSUE THREAD

**Issue by NovaDev94** [joshdick/onedark.vim#107]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

Terminal: iTerm 2 (3.0.15) on Mac OS 10.11

### Output From `vim --version`

```
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-20108-3wengs/neovim-0.2.0/build/config -I/tmp/neovim-20170707-20108-3wengs/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170707-20108-3wengs/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-20108-3wengs/neovim-0.2.0/build/include
Compiled by brew@ElCapitan.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"
```

### Issue Description

Diff lines being extremely hard to see with `cursorline` on (as you can see on line 7 on the right pane)

![image](https://user-images.githubusercontent.com/6073918/29270303-594d1136-8120-11e7-97b1-152665b4e930.png)

**Comment by silenc3r** [comment]
I just came here to report the very same issue. The line the cursor is at is usually completely unreadable.

**Comment by joshdick** [comment]
Just pushed a fix that uses underline styling instead of background styling for `cursorline` when in diff mode.

Hope that's a good workaround. 🙂 

Example:

<img width="1249" alt="screen shot 2017-08-15 at 7 18 28 pm" src="https://user-images.githubusercontent.com/424691/29340817-ff2ca1c4-81ee-11e7-9554-9be800c0ef62.png">

**Comment by silenc3r** [comment]
Great, thanks!

**Comment by tmccombs** [comment]
I still have this problem:
![image](https://user-images.githubusercontent.com/2541726/70119566-c4d43a80-1627-11ea-8f8a-b2b64f9a6b78.png)

Both the foreground and background are dark, making the diff practically impossible to read.

**Comment by joshdick** [comment]
@tmccombs Are you using the latest version of `onedark.vim`? What version of vim are you using?

**Comment by tmccombs** [comment]
vim version:
```
➜ nvim --version
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-_mzR4z/neovim-0.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-_mzR4z/neovim-0.2.2/build/config -I/build/neovim-_mzR4z/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-_mzR4z/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-_mzR4z/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

onedark is on commit a5c74e9d1877e9ade09b8c9b65fc946958f2c979

**Comment by joshdick** [comment]
@tmccombs OK, you're using the latest `onedark.vim`, but that's a relatively old version of Neovim. I wonder if using a newer one would clear up this issue for you.

**Comment by tmccombs** [comment]
It does look like it is fixed in the latest version of nvim. Unfortunately 0.2.2 is the latest version available on ubuntu 18.04. :(

**Comment by joshdick** [comment]
@tmccombs There's unfortunately not much I can do about that. 😕 Perhaps you could try compiling neovim yourself?

**Comment by nkcfan** [comment]
This is reproducible in terminal vim 8.2.
However in neovim 0.4.3 in GUI (nvim-qt) is pretty fine.
