### ISSUE TITLE
Airline colors

### ISSUE THREAD

**Issue by zackhsi** [joshdick/onedark.vim#108]
Hi, me again!

A [recent change to vim-airline](https://github.com/vim-airline/vim-airline/commit/c65d7fe36b9d4d6f779725be86d71c4aa0257e01) broke the onedark airline theme for me.

Before:
![screen shot 2017-08-18 at 4 10 48 pm](https://user-images.githubusercontent.com/806101/29480868-91935650-8430-11e7-9767-597c049b308d.png)

After:
![screen shot 2017-08-18 at 4 11 01 pm](https://user-images.githubusercontent.com/806101/29480872-98851458-8430-11e7-9e4e-6117145a47b1.png)

I'm unclear if it's an issue with vim-airline or with the onedark airline theme.

**Comment by plexigras** [comment]
it works for me.

**Comment by zackhsi** [comment]
Using what revisions for airline and onedark?

**Comment by plexigras** [comment]
the newest

**Comment by zackhsi** [comment]
Turns out if was an airline bug.

- https://github.com/vim-airline/vim-airline/commit/470e9870f13830580d1938a2dae1be5b6e43d92a
- https://github.com/vim-airline/vim-airline/issues/1531

**Comment by baco** [comment]
It still happens to me
