### ISSUE TITLE
Neovim Whitespace (listchars) color

### ISSUE THREAD

**Issue by Vintodrimmer** [joshdick/onedark.vim#111]
I suppose it's more of a feature request than a bug.

Neovim has introduced special 'Whitespace' highlight group, so all the affected characters are the color of `Nontext` if I'm not mistaken, as is mentioned [here](https://github.com/neovim/neovim/pull/6367).

Could you incorporate the group colors into your theme, please?

Without them (or some workaround), these characters are almost impossible to see (as shown in the highlighted line in the screenshot).

![screenshot with trailing spaces and tabs hardly](https://raw.githubusercontent.com/Vintodrimmer/docs/master/2017-11-09-10%3A11%3A35-screenshot.png)

Here is the relevant part from the `:help listchars`: 

> hl-NonText highlighting will be used for "eol", "extends" and "precedes". hl-Whitespace for "nbsp", "space", "tab" and "trail".

I use `st` as a terminal emulator and `Neovim 0.2.1`

```
NVIM v0.2.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/lib/ccache/bin/cc -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe  -g -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/builddir/neovim-0.2.1/build/config -I/builddir/neovim-0.2.1/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/builddir/neovim-0.2.1/build/src/nvim/auto -I/builddir/neovim-0.2.1/build/include
Compiled by void-buildslave@build

Features: +acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by joshdick** [comment]
The documentation in that PR does say `By default, +|hl-Whitespace| is linked to |hl-NonText|.`

In `onedark.vim`, `NonText` and `SpecialKey` highlights actually use the same color, so the theme appears to still be rendering as intended even with NeoVim's `Whitespace` change.

You can override `NonText`, or add a new highlight for `Whitespace`, in your `~/.vimrc` by using onedark.vim's [customization mechanism](https://github.com/joshdick/onedark.vim#customizing-onedarkvims-look-without-forking-the-repository).
