### ISSUE TITLE
Too bright comments

### ISSUE THREAD

**Issue by JozefFlakus** [joshdick/onedark.vim#117]
I've encountered a problem with comments highlighting in `16 color mode`.
Here is my `.vimrc` config:

```
let g:onedark_termcolors=16
let g:onedark_terminal_italics=1

syntax on
colorscheme onedark
set background=dark

let g:airline_theme='tomorrow'
let g:tsuquyomi_completion_detail=1


"Omnicompletion
set completeopt=longest,menuone

if !exists("g:ycm_semantic_triggers")
  let g:ycm_semantic_triggers = {}
endif

let g:ycm_semantic_triggers['typescript'] = ['.']

"Show line numbers
set number

"Convert tabs into 2 spaces
set expandtab
set tabstop=2

"Highlight comments
highlight Comment cterm=italic
```

In `256 color mode` it looks better but the background is darkened - known issue, but I have no idea why in `16 color mode` there is such difference in comments bright.

---
**I'm using it with `iTerm2`.**

<img width="545" alt="zrzut ekranu 2018-03-12 o 00 14 44" src="https://user-images.githubusercontent.com/7793430/37259757-c6fd7d24-258a-11e8-9360-9ec0bff7642f.png">

**Comment by joshdick** [comment]
What terminal emulator are you using? How did you install One Dark's 16-color terminal theme?

**Comment by JozefFlakus** [comment]
Ok it works! I totally missed the point about color scheme step from `term/One Dark.Xresource`.

Problem solved!

**Comment by joshdick** [comment]
There is a `term/One Dark.itermcolors` that you can use directly with `iTerm2` provided that you're using a version of `iTerm` >= 2.9.x.

Not sure what you did to fix it, but I'm glad it's working.
