### ISSUE TITLE
Background color not same like demo in this repository

### ISSUE THREAD

**Issue by sgnd** [joshdick/onedark.vim#122]
I run vim in my ubuntu wsl in windows 10. This is my configuration in `.vimrc`
```
let g:airline_theme='onedark'
let g:onedark_termcolors=256
colorscheme onedark
```
![image](https://user-images.githubusercontent.com/15070585/39968267-ab176b74-56f4-11e8-83f9-b7603258b45d.png)

How to fix this?

**Comment by joshdick** [comment]
That's what onedark.vim looks like in 256-color mode, which is how you've configured it.

To get the colors to look like the screenshot, you need to configure it to use true color mode (preferred) or 16-color mode (if true color mode doesn't work in your version of Vim/terminal emulator.)

See the README for more details.
