### ISSUE TITLE
Change background color?

### ISSUE THREAD

**Issue by karambaq** [joshdick/onedark.vim#123]
Hey, sorry for noob question, but how can I change the background color?
I tried to change colors in autoload/onedark.vim but that doesn't work.
Thank you!

**Comment by joshdick** [comment]
Which thing to change depends on which version of Vim you're using, where you're using it (terminal or GUI), and the value of your `g:onedark_termcolors` setting.

I can help more if you tell me that information. 🙂

**Comment by karambaq** [comment]
@joshdick 
NVIM v0.2.2
iTerm2
256

**Comment by joshdick** [comment]
You should be able to do something like this:

```vim
"onedark.vim override: Set a custom background color in the terminal
if (has("autocmd") && !has("gui_running"))
  augroup colors
    autocmd!
    let s:background = { "gui": "#282C34", "cterm": "235", "cterm16": "0" }
    autocmd ColorScheme * call onedark#set_highlight("Normal", { "bg": s:background }) "No `fg` setting
  augroup END
endif
```

Since you're using 256-color mode, changing the value of `cterm` should change the background color (color values are listed [https://jonasjacek.github.io/colors/](here)). 256-color mode settings won't apply if you use `set termguicolors`; you'll have to change the value of `gui` instead.

That should do it, so I'm going to close this issue, but feel free to continue the conversation if you need more help!

**Comment by karambaq** [comment]
@joshdick I comment out `set termguicolors` and add what you said in the config and here is result:

<img width="1440" alt="2018-05-30 22 44 41" src="https://user-images.githubusercontent.com/14233969/40743866-661fbb56-645b-11e8-9f91-c7a7ba582bd6.png">

**Comment by joshdick** [comment]
`set termguicolors` will give you better colors, so you should uncomment it. Like I said, with `set termguicolors` on, change the value of `gui` (`"#282C34"` in the snippet I gave you) to a different hex color, whatever color you want the background to be. For example, `"#FF0000"` would be red.

**Comment by karambaq** [comment]
@joshdick oh, sorry, I'm not so good in English :)
Here is a error on start:
<img width="787" alt="2018-05-30 22 54 39" src="https://user-images.githubusercontent.com/14233969/40744202-84d8cce4-645c-11e8-90d2-63622b439e6e.png">

**Comment by joshdick** [comment]
Are you using the latest version of onedark.vim? Was that error happening the first time you pasted in the config I gave you earlier?

**Comment by karambaq** [comment]
Yes
<img width="787" alt="2018-05-30 23 01 11" src="https://user-images.githubusercontent.com/14233969/40744497-5fd7c250-645d-11e8-9bd2-22fbf49a0281.png">

I add this in config, launch nvim, background doesn't change, I tried to source `~/.config/nvim/init.vim` and this error is happens

**Comment by joshdick** [comment]
The background isn't changing because the config snippet you pasted in is commented out.

You need to paste the snippet before the `colorscheme onedark` line in your config.

**Comment by karambaq** [comment]
I'm not that stupid haha :)
<img width="1440" alt="2018-05-30 23 09 03" src="https://user-images.githubusercontent.com/14233969/40744852-806a6364-645e-11e8-88e2-462fe5d9e7b0.png">

It's says:
Error detecting while processing Colorscheme Auto commands for "*":
Unknown function: onedark#set_highlight

**Comment by joshdick** [comment]
What plugin loader are you using? Can you paste your entire nvim config somewhere?

**Comment by karambaq** [comment]
It seems like flazz/vim-colorschemes plugin includes onedark theme, because after I trying to delete your plugin nothing changes, after that I delete vim-colorschemes plugin, and installs yours, after that I can change the background color using your snippet
Thank you for you help!

**Comment by joshdick** [comment]
You're welcome!

**Comment by karambaq** [comment]
Also, how can I change the syntax color behavior, for example, I want that 'import' in python be purple 

is it okay that I asking it here, or better open another issue? 
thank you

**Comment by joshdick** [comment]
You can use a similar pattern to how you changed the background color, but you'll need to know the name of the highlight group to change in addition to "Normal" which is the one that was used to change the background in the snippet above.

You can use this code to figure out the highlight group name by placing your cursor over the text you want to change and hitting F10: http://vim.wikia.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor

**Comment by karambaq** [comment]
Thank you so much!

**Comment by joshdick** [comment]
You're welcome!
