### ISSUE TITLE
Function name can't be highlighted

### ISSUE THREAD

**Issue by sunshoe** [joshdick/onedark.vim#125]
### Issue Description
I'm using MacVim with onedark theme, the color of "Function" is aways white, and it can't be change any color else,  i even tried change "Function" tag  to "Method", it doesn't work either. That made me so confused.

![image](https://user-images.githubusercontent.com/24785546/41735098-6634cede-754e-11e8-82b8-42fb4b7224de.png)

**Comment by simonsmith** [comment]
See this comment for how to work out what highlight group applies to that keyword - https://github.com/joshdick/onedark.vim/issues/123#issuecomment-393336758

**Comment by sunshoe** [comment]
Well I have seen this comment, but it doesn't include my case i guess ..

**Comment by simonsmith** [comment]
What highlight group is reported when you hit F10?

**Comment by sunshoe** [comment]
Here is 

![image](https://user-images.githubusercontent.com/24785546/41738710-6d412d8a-7558-11e8-9a53-710c9c8900a0.png)

**Comment by sunshoe** [comment]
I have changed some highlight groups' colour to purple, this is the only modification i have made.
![image](https://user-images.githubusercontent.com/24785546/41738886-f3f035f6-7558-11e8-8f5d-03d8b23e20f7.png)

**Comment by joshdick** [comment]
Do you have something like the following lines near the top of your `~/.vimrc`? If not, do things start working if you add them?

```
filetype plugin on
syntax on
```

**Comment by sunshoe** [comment]
Yes , i have 

![image](https://user-images.githubusercontent.com/24785546/41739484-cfde165e-755a-11e8-976c-1cac03281c71.png)

**Comment by sunshoe** [comment]
I noticed function name can be highlighted in .py,  .vim, but not in .cpp, .c, .js

**Comment by sunshoe** [comment]
After a full day of trying i discovered that maybe it was a bug of vim itself,  none of built-in theme could highlight function nor operator in C or C++ correctly, then i download a plugin , here is https://github.com/octol/vim-cpp-enhanced-highlight
Which works well after making some modification.
![image](https://user-images.githubusercontent.com/24785546/41804751-717af5ca-7661-11e8-930a-cb052436ad70.png)

**Comment by sunshoe** [comment]
Well thank you guys for trying to help me,  this issue could be closed 👌

**Comment by joshdick** [comment]
Glad you got things working. You may also have some luck with the [vim-polyglot](vim-polyglot
) plugin.

**Comment by sunshoe** [comment]
Thank you @joshdick , i got it
