### ISSUE TITLE
Brownish background in vim in iTerm2

### ISSUE THREAD

**Issue by bk2dcradle** [joshdick/onedark.vim#13]
So I installed onedark for iTerm2 and Vim as well. But it doesn't look right when I am using Vim in iTerm2 or even system terminal. Though it looks fine in MacVim.

As you can see, theme looks great in MacVim, great in iTerm but not so when Vim is opened inside iTerm

![screenshot](https://raw.githubusercontent.com/bk2dcradle/assets/master/onedarkissue.png)

**Comment by joshdick** [comment]
This is happening because the theme is running in 256-color mode in iTerm2.

To see proper colors in iTerm2, you need to switch to 16-color mode as described at the bottom of the README: https://github.com/joshdick/onedark.vim#16-color-mode

**Comment by bk2dcradle** [comment]
I did install `One Dark.itermcolors` and I am using it. Also I have this in my `vimrc`. 

```vim
colorscheme onedark
let g:airline_theme='onedark'
let g:onedark_termcolors=16
```

Still it's not working

**Comment by joshdick** [comment]
Try putting the `let g:onedark_termcolors=16` line before the `colorscheme onedark` line.

**Comment by joshdick** [comment]
It looks like you were probably using the color schemes from [this project](https://github.com/nathanbuchar/atom-one-dark-terminal).

I'm not sure why iTerm wouldn't switch colors when picking the scheme from this repository. Maybe try deleting the other One Dark themes?

**Comment by bk2dcradle** [comment]
I tried deleting both of the `1.0.0` versions and your version, then reimported your version, still `iTerm` isn't recognizing it.

**Comment by joshdick** [comment]
What version of iTerm2 are you using?

**Comment by bk2dcradle** [comment]
2.1.4

**Comment by joshdick** [comment]
Would you mind seeing if 2.9 (test release) makes a difference? The color scheme formats does appear to have changed.

**Comment by bk2dcradle** [comment]
I am trying right now. Though it will take some time, internet in my dorm is not "praiseworthy". What I tried in the mean time was to rename the `termcolors` file that you provided, thinking that the error might because of failed name resolution. That didn't work either.

**Comment by bk2dcradle** [comment]
It seems to be working now. I am using the 2.9 beta version of iTerm. Thanks

**Comment by joshdick** [comment]
Cool, glad we figured it out!

**Comment by bk2dcradle** [comment]
Hey can you tell me how exactly I can edit the color scheme. Basically I want to change the incsearch color to something that is prominent, like dark_yellow. I tried setting the value in line 154 of `onedark.vim` but it didn't change anything.

Also can you address this issue in general ? incsearch's color is visual black, which is barely visible, especially considering the fact that incsearch's color should be prominent so it kind of stands out from the rest of the code.

**Comment by joshdick** [comment]
You can change the values of the "fg" and "bg" properties on any line to the variable names defined in the "Color Variables" section of the file. Omitting either property will use default/existing colors for that property.

I made IncSearch match visual mode highlighting since that was my preference, but you can change it to suit your needs; one possible combination is white foreground and red background.

If you choose to set a background color, the foreground color should also be set to something specific (black in the current case), because when using a set background color like red, if red text happens to be highlighted, it would be unreadable (red text on a red background.)

**Comment by bk2dcradle** [comment]
Why doesn't this work, to change the color for IncSearch

```vim
call s:h("IncSearch", { "fg": s:dark_yellow, "bg": s:visual_grey }) " 'incsearch' highlighting; also used for the text replaced with ":s///c"

```

**Comment by joshdick** [comment]
That works just fine for me. Did you re-source .vimrc or restart Vim after making the change?

**Comment by bk2dcradle** [comment]
Yup did resource `.vimrc`, even restarted `iTerm`. The problem is `onedark.vim` is not loading for some reason.

**Comment by joshdick** [comment]
Do you see any errors in Vim on startup?

Are you editing the correct copy of the theme (maybe you have one being loaded by a plugin manager and one in the normal colors directory?)

**Comment by bk2dcradle** [comment]
It's working now, deleted the old copy and cloned it again in bundle. Thanks anyways !

**Comment by joshdick** [comment]
You're welcome!
