### ISSUE TITLE
Receiving Unknown Function and Invalid Expressions

### ISSUE THREAD

**Issue by rr0ss0rr** [joshdick/onedark.vim#131]
Hi .. I'm receiving the following (multiple screens) after installing colors/onedark.vim into .vim/colors and setting onedark as the colorscheme in .vimrc.  This is on a iterm2 (256 colors) macvim install on a Mac.  I figure line 133 error is the culprit, but not sure how to fix.  One Dark.itermcolors works fine on iterm.  Thanks

line  133:
E117: Unknown function: onedark#GetColors
E15: Invalid expression: onedark#GetColors()
line  135:
E121: Undefined variable: s:colors
E15: Invalid expression: s:colors.red
line  136:
E121: Undefined variable: s:colors
E15: Invalid expression: s:colors.dark_red

**Comment by joshdick** [comment]
You're most likely missing `autoload/onedark.vim` in your `~/.vim/autoload/` directory.

Please review the [installation instructions](https://github.com/joshdick/onedark.vim#installation) carefully.

**Comment by rr0ss0rr** [comment]
That was it .. I guess I never used a colorscheme that required placing the file in autoload (the directory didn't exist).  Thanks for the quick response

**Comment by joshdick** [comment]
No problem, you're welcome.

**Comment by kalindu1** [comment]
I am getting the same issue. I did what you said by putting autoload/onedark.vim in my ~/.vim/autoload/ but it didn't work.
