### ISSUE TITLE
Add support for :Termdebug highlight groups

### ISSUE THREAD

**Issue by BojanStipic** [joshdick/onedark.vim#136]
Vim 8.1 added support for GDB debugger (`:h :Termdebug`).

There are 2 new highlight groups for this (`:h hl-debugPC`, `:h hl-debugBreakpoint`):
* `debugPC` - the current position
* `debugBreakpoint` - a breakpoint

This color scheme is missing these.

**Comment by BojanStipic** [comment]
Thank you @joshdick!

**Comment by joshdick** [comment]
@bojanstipic You're welcome, sorry it took so long!
