### ISSUE TITLE
A tip for too bright comments in iTerm2

### ISSUE THREAD

**Issue by bsod90** [joshdick/onedark.vim#145]
This is not a bug report, but rather a tip that could be added to a Troubleshooting section.
I've been struggling with a comment color for my python code for a while. Basically, all the comments looked the same as the normal code. Recently I finally spent some time troubleshooting it, and found an interesting iTerm2 option, which I didn't know existed, and which drastically affects all the colors displayed. Here's the GIF:
![screen capture on 2019-01-14 at 17-14-06](https://user-images.githubusercontent.com/2292499/51151654-71df7200-1820-11e9-9a4a-bf9f4cfa90af.gif)

What I think is happening is iTerm2 tries to make sure there's always enough contrast between the text and the background, and it's able to tweak displayed colors for that even through the exact values are specified.
Again, this is a feature, not a bug, but I'm sure it may confuse a lot of people who do not know it exists.

**Comment by joshdick** [comment]
iTerm 2 is my primary terminal emulator and I've always run it with the Minimum Contrast slider turned all the way down.

Nice catch, I've added a note to the troubleshooting section of the README in 682f866.
