### ISSUE TITLE
MatchParen  as bold ? 

### ISSUE THREAD

**Issue by zamaterian** [joshdick/onedark.vim#15]
When using Rainbow parens, the matching paren is hard to see because of color reuse. How do I set it as Bold ?

**Comment by joshdick** [comment]
You should be able to accomplish that by changing the `MatchParen` line to this:

`call s:h("MatchParen", { "fg": s:blue, "cterm": "bold", "cterm16": "bold", "gui": "underline" }) " The character under the cursor or just before it, if it is a paired bracket, and its match.`

You can change the `"gui"` property to `"bold"` as well, if that suits you.
