### ISSUE TITLE
onedark no longer working?? after Macvim update (Patch 155)

### ISSUE THREAD

**Issue by rr0ss0rr** [joshdick/onedark.vim#151]
macvim was updated last night on my Mac and am now receiving the following errors (Thousands of them).  I'm assuming it's onedark since mccvim is defaulting to some other color scheme.  Any idea what the issue could be?  onedark is installed via vim-plug and is at the latest version.

VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2019 12:07:03)
macOS version
Included patches: 1-950

line 13:
E461: Illegal variable name: a:highlight
line 14:
E121: Undefined variable: a:highlight
line 18:
E121: Undefined variable: a:highlight
E116: Invalid arguments for function has_key(a:highlight, "cterm") && a:highlight["cterm"] == "italic"
line 21:
E121: Undefined variable: a:highlight
E116: Invalid arguments for function has_key(a:highlight, "gui") && a:highlight["gui"] == "italic"
line 30:
E121: Undefined variable: a:highlight
E116: Invalid arguments for function has_key(a:highlight, "fg") ? a:highlight.fg.cterm : "NONE")
line 31:
E121: Undefined variable: a:highlight
E116: Invalid arguments for function has_key(a:highlight, "bg") ? a:highlight.bg.cterm : "NONE")
line 34:
E121: Undefined variable: a:highlight
E116: Invalid arguments for function has_key(a:highlight, "fg") ? a:highlight.fg.gui : "NONE") "guibg=" (has_key(a:highlight, "bg") ? a:highlight.bg.gui : "NONE") "guisp=" (has_key(a:highlight, "sp") ? a:highlight.sp.gui : "NONE") "gui=" (has_key(a:highlight, "gui") ? a:highlight.gui : "NONE") "ctermfg=" . l:ctermfg "ctermbg=" . l:ctermbg "cterm=" (has_key(a:highlight, "cterm") ? a:highlight.cterm : "NONE")

**Comment by joshdick** [comment]
This looks a lot like https://github.com/joshdick/onedark.vim/issues/148 which was already fixed, are you sure you're using the latest version of onedark.vim?

**Comment by rr0ss0rr** [comment]
vim-plug says I am ...

Updated. Elapsed time: 0.629680 sec.
[===]

- Finishing ... Done!
- lightline.vim: Already up to date.
- onedark.vim: Already up to date.
- vim-shfmt: Already up to date.

**Comment by rr0ss0rr** [comment]
I was probably on patch 154 prior to last nights update which equates to 8.1.873 ... so this is the 1st time since I'm >= 8.1.888

**Comment by joshdick** [comment]
It does seem like you're running an old version of onedark.vim, since all of the `a:highlight`s have since been changed to `s:highlight`s.

Some possibilities:

* There could be multiple copies of onedark.vim in your Vim configuration
* You could be using a plugin that contains an old version of onedark.vim (for example, SpaceVim, or a colorscheme pack)
* vim-plug is somehow lying to you and not actually updating onedark.vim

Maybe doing the following would show if there was an old, rogue copy of onedark.vim kicking around in your configuration?

```bash
cd ~/.vim
grep -R 'a:highlight' .  | grep onedark
```

**Comment by rr0ss0rr** [comment]
yup .. .vim/colors does have a old copy of onedark.vim ... .vim/plugged does have the current onedark repository .. so I guess it's a vim-plug issue .. Thanks

**Comment by joshdick** [comment]
You're welcome, seems like deleting the copy in `.vim/colors` should fix the problem then.

In light of that, I'm going to close this issue, but feel free to keep the conversation going if needed.

**Comment by rr0ss0rr** [comment]
Thanks again .. one question .. does onedark support vim-plug?

**Comment by joshdick** [comment]
It should!

**Comment by joshdick** [comment]
I haven't used vim-plug in some time, but from what I remember, it should not be placing anything in `~/.vim/colors`, only in `~/.vim/plugged`; it's likely that the old copy in `~/.vim/colors` was placed there manually.

**Comment by rr0ss0rr** [comment]
Thanks for your help .. My old Mac crapped out and got a new one .. I thought I was careful with just restoring a minimal set and rebuilding from scratch.  I looks like I restored a copy of my .vim directory that had all the old folders in it.  I'm back to normal now .. thanks

**Comment by joshdick** [comment]
No problem, you're welcome!
