### ISSUE TITLE
Support for tex

### ISSUE THREAD

**Issue by Donkeyfish87** [joshdick/onedark.vim#158]
I've made some customisations of this for vimtex/latex, and thought I'd eventually make a pr. Is it preferable to write in the syntax groups that remains default explicitly? That would add clarity for what groups that exists, but would add lines to the file that technically does nothing.

I'd thought I'd make a middle ground, writing in the ones that are "big". Like e.g. texBeginEnd - which should appear many times in almost any tex document.

I've also colorised greek letters in math mode, which I reckon is quite opinionated. I like it, but many might find it too fruit-salady.

**Comment by joshdick** [comment]
> Is it preferable to write in the syntax groups that remains default explicitly?

No. 🙂

> I'd thought I'd make a middle ground, writing in the ones that are "big".

Perfect.

> many might find it too fruit-salady.

Then I wouldn't put that in the PR.

Thanks for your interest in contributing to onedark.vim!

**Comment by Donkeyfish87** [comment]
Made a pr just now. Aimed at keeping it fairly clean, but can't say 
i'm a graphical designer of any kind :)

**Comment by joshdick** [comment]
Implemented in #159.
