### ISSUE TITLE
Have trouble displaying on iTerm2

### ISSUE THREAD

**Issue by p-z-l** [joshdick/onedark.vim#162]
**My onedark.vim works totally fine on MacVim**
<img width="1201" alt="Screen Shot 2019-04-07 at 4 46 44 PM" src="https://user-images.githubusercontent.com/43706386/55681088-bdec0f80-5954-11e9-9337-d280ca63a4d4.png">

*But here's what it looks like under iTerm2*
<img width="962" alt="Screen Shot 2019-04-07 at 4 47 20 PM" src="https://user-images.githubusercontent.com/43706386/55681090-d2c8a300-5954-11e9-9e4d-89f90212bef6.png">

And it looks even worse under tmux
<img width="1340" alt="Screen Shot 2019-04-07 at 4 49 53 PM" src="https://user-images.githubusercontent.com/43706386/55681122-2d61ff00-5955-11e9-9493-db5ef0f4888c.png">

Any ideas I how could fixed it?

P.s. I use Vim (instead of Neovim)

**Comment by joshdick** [comment]
It looks like the theme is running in 256-color mode.

Did you follow the [installation instructions](https://github.com/joshdick/onedark.vim/blob/master/README.md#installation) in the README?

**Comment by p-z-l** [comment]
Yeah, I think so.

And I'm pretty sure that my iTerm2 is 256-color enabled

<img width="541" alt="Screen Shot 2019-04-07 at 8 15 44 PM" src="https://user-images.githubusercontent.com/43706386/55683414-18479900-5972-11e9-96df-494b6ff22a5d.png">

**Comment by joshdick** [comment]
You need to enable 24-bit/true color mode as outlined in the instructions and not use 256-color mode.

**Comment by p-z-l** [comment]
Deal with it

THANKS. VERY. MUCH

**Comment by joshdick** [comment]
?

**Comment by p-z-l** [comment]
i mean.  i deleted previous install data and reinstalled it following the instructions.
and i solved the problem

**Comment by joshdick** [comment]
Oh I see, glad you got it working!
