### ISSUE TITLE
Request: Split special_grey

### ISSUE THREAD

**Issue by EarthCitizen** [joshdick/onedark.vim#169]
I like to enable the following setting: `set list lcs=eol:¬,space:·,tab:»\`. And `special_grey` has a good default for this case, which is fairly dim, and desirable.

The problem I have is that when entering the following command:
`:<CTRL-V><CTRL-C>` (for example) I get the text `^C`, but `special_grey` seems to also determine this color, which is too dim to be readable. When I brighten `special_grey`, I can read `^C` in commands, but this makes the dot characters for the spaces distracting.

Is it possible to separate these two colors into separate groups?

**Comment by joshdick** [comment]
Unfortunately, it is not possible to separate these in a way that is portable and consistent across all Vims.

In Vim, listchars and the `^C` you mentioned in command-line mode are both highlighted with the `SpecialKey` highlight group. Neovim appears to not use `SpecialKey` for listchars, so **it would be possible to get the result you're after if you use Neovim and override the `SpecialKey` highlight group** as documented here: https://github.com/joshdick/onedark.vim#customizing-onedarkvims-look-without-forking-the-repository

I hope that helps!

**Comment by EarthCitizen** [comment]
@joshdick Thanks. I will give that a shot.

**Comment by joshdick** [comment]
You're welcome!

**Comment by EarthCitizen** [comment]
I forgot to mention that I am using Neovim.
