### ISSUE TITLE
Commented text color same as highlight color

### ISSUE THREAD

**Issue by zackhsi** [joshdick/onedark.vim#17]
Great theme, thanks!

When I highlight a word that is commented out, the text is not legible :(

![highlight comment](https://cloud.githubusercontent.com/assets/806101/14392296/851c1a44-fd75-11e5-823e-c834b44d5f11.png)

**Comment by joshdick** [comment]
Fixed, thanks for the report!

**Comment by zackhsi** [comment]
:100: thanks for the quick fix!

**Comment by joshdick** [comment]
You're welcome!

**Comment by blackbing** [comment]
still have the same problem. I use the latest version.
