### ISSUE TITLE
What fonts are used in this presentation screenshot ?

### ISSUE THREAD

**Issue by cata0309** [joshdick/onedark.vim#176]
![image](https://user-images.githubusercontent.com/35623921/62851147-e2366f00-bced-11e9-9cc8-63fdfb7bac4d.png)

**Comment by simonsmith** [comment]
At the bottom of the README:

> 13 pt. [PragmataPro Mono](http://www.fsd.it/fonts/pragmatapro.htm#.VlDa1q6rTOY) font

:)

**Comment by cata0309** [comment]
I also meant the "onedark.vim" font

**Comment by joshdick** [comment]
The font in the title is [Input Mono](https://input.fontbureau.com/) with the "Pragmata Pro" style selected on the download page.

**Comment by cata0309** [comment]
Thank you @joshdick

**Comment by joshdick** [comment]
You're welcome @cata0309!
