### ISSUE TITLE
Colors vary between Macvim and vim + iterm

### ISSUE THREAD

**Issue by wheredoesyourmindgo** [joshdick/onedark.vim#18]
Seems like the vim theme works well using mvim, however, the colors seem off when using vim 7.4 within iterm and terminal app.  Any thoughts? Screen capture depicts vim+iTerm on left and mvim on right. 

<img width="600" alt="screen shot 2016-04-12 at 6 27 55 am" src="https://cloud.githubusercontent.com/assets/3316678/14461653/5c7d24a6-0078-11e6-8651-b5f60d33ea5a.png">

**Comment by joshdick** [comment]
Which version of iTerm are you using? The color theme only supports iTerm2 2.9+.

**Comment by wheredoesyourmindgo** [comment]
I'm using iTerm Build 2.9.20160313.  I get the same color variation using Apple's Terminal app

**Comment by wheredoesyourmindgo** [comment]
I should note that the iTerm color scheme looks great.

**Comment by jlobos** [comment]
occurs the same in xterm and termite
![2016-04-12-12 54 34](https://cloud.githubusercontent.com/assets/11975868/14471868/f8eb09cc-00c6-11e6-8350-2bde95e59227.png)

**Comment by joshdick** [comment]
I should have noticed this earlier: It looks like the color scheme is using 256-color mode in both cases mentioned above.

Provided that you're both **using the official 16-color terminal color theme**, you are likely missing the line `let g:onedark_termcolors=16` in your `.vimrc`. That line should appear before `colorscheme onedark`.

**Comment by jlobos** [comment]
i run `NVIM_TUI_ENABLE_TRUE_COLOR=1 nvim` and found correct colors :heart_eyes:

**Comment by joshdick** [comment]
@jlobos Great, I've updated README.md with some additional information about Neovim and this setting (see 11d9b4f).

@wheredoesyourmindgo I'm going to close this issue, but feel free to leave another comment if the mentioned solution doesn't work for you.

**Comment by wheredoesyourmindgo** [comment]
@joshdick I tried `let g:onedark_termcolors=16` before opening the ticket.  Like you mentioned above, placing that _before_ `colorscheme onedark` worked for me.  Thanks for the clarification.

**Comment by joshdick** [comment]
@wheredoesyourmindgo Glad we got it sorted out! I've added some clarifying comments to the README in ff39b10.
