### ISSUE TITLE
Onedark colorscheme is not displaying correctly in vim8

### ISSUE THREAD

**Issue by willyamwu** [joshdick/onedark.vim#182]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info
I am using ITerm2 and Vim 8

### Output From `vim --version`

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  5 2019 21:03:34)
Included patches: 1-503, 505-680, 682-1312
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl               +extra_search      -mouse_netterm     -tag_old_static
-arabic            -farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      -mouse_urxvt       -termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
-balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
+builtin_terms     -gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        -toolbar
-clientserver      +job               -perl              +user_commands
-clipboard         +jumplist          +persistent_undo   -vartabs
+cmdline_compl     -keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      -langmap           -profile           +visual
+comments          +libcall           +python/dyn        +visualextra
-conceal           +linebreak         -python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          -rightleft         +wildmenu
+cursorshape       -lua               +ruby/dyn          +windows
+dialog_con        +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             -X11
+digraphs          +modify_fname      +smartindent       -xfontset
-dnd               +mouse             +startuptime       -xim
-ebcdic            -mouseshape        +statusline        -xpm
-emacs_tags        -mouse_dec         -sun_workshop      -xsmp
+eval              -mouse_gpm         +syntax            -xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa
```

### Issue Description
In Vim8, vim can't display the correct one dark color. I have seen two previous posts on this issue that have the same problem. I tried all of the methods and walked through the install guide, but still have no luck finding why vim is displaying the wrong color. My macvim that is running inside my terminal can display the correct color, but not the normal vim. I have set the report terminal type as xterm-256color, put ```export TERM=xterm-256color``` in .bashrc, and below is a screenshot of my vimrc. Here is the full config if you need: https://github.com/willyamwu/dot-vim
I did notice something weird when I tried the ```printf "\x1b[38;2;255;100;0mTRUECOLOR\x1b[0m\n"``` command and apparently my terminal is printing orange instead of red. But I checked the 24bit true color list and iterm is one of them, so it should be supporting 24bit color.
<img width="527" alt="Screen Shot 2019-09-25 at 3 24 59 PM" src="https://user-images.githubusercontent.com/23061464/65636822-ad822c80-dfa8-11e9-81ff-597fcfa998df.png">

<img width="713" alt="Screen Shot 2019-09-25 at 3 09 41 PM" src="https://user-images.githubusercontent.com/23061464/65635976-fcc75d80-dfa6-11e9-9e74-5b50829f00cd.png">

<img width="715" alt="Screen Shot 2019-09-25 at 2 59 57 PM" src="https://user-images.githubusercontent.com/23061464/65635340-bf160500-dfa5-11e9-9662-9051ac1ec8bc.png">
<img width="710" alt="Screen Shot 2019-09-25 at 3 00 21 PM" src="https://user-images.githubusercontent.com/23061464/65635345-c1785f00-dfa5-11e9-929e-914fa6469418.png">

**Comment by willyamwu** [comment]
Never mind, I figured out. I installed vim through brew, and the vim from that is displaying the correct color.

**Comment by vtmx** [comment]
.tmux.conf
```set-option -ga terminal-overrides ",xterm-256color:Tc"```
