### ISSUE TITLE
"Pattern not found" when setting variables

### ISSUE THREAD

**Issue by chinmaychhajed** [joshdick/onedark.vim#186]
Hello,

Terminal: `konsole`
`konsole --version`: `konsole 17.12.3`.
`vim --version`: 8.0.1453

I use `Vundle` as my plugin manager. After installing by adding `Plugin 'joshdick/onedark.vim'`, I added following lines in my .vimrc:
```
g:onedark_hide_endofbuffer=1
g:onedark_termcolors=256
g:onedark_terminal_italics=1
colorscheme onedark
```

Whenever I open vim then following error show up:
```
$ vim
Pattern not found: onedark_hide_endofbuffer=1
Pattern not found: onedark_termcolors=256
Pattern not found: onedark_terminal_italics=1
Press ENTER or type command to continue
```

I would like to know what is causing this issue and how I can get rid of it. Most probably rest of the colorscheme is working fine.
Thanks in advance.

**Comment by joshdick** [comment]
The onedark.vim settings lines in your `.vimrc` is missing the `let` keyword; they should look like this:

```viml
let g:onedark_hide_endofbuffer=1
let g:onedark_termcolors=256
let g:onedark_terminal_italics=1
colorscheme onedark
```
