### ISSUE TITLE
.json highlighting

### ISSUE THREAD

**Issue by fbaltor** [joshdick/onedark.vim#193]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [X] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info
$ xprop _NET_WM_PID WM_CLASS
_NET_WM_PID(CARDINAL) = 2994
WM_CLASS(STRING) = "gnome-terminal-server", "Gnome-terminal"

$ ls -l /proc/$$/exe
lrwxrwxrwx 1 fbaltor fbaltor 0 nov 27 15:36 /proc/5852/exe -> /usr/bin/bash

### Output From `nvim --version`

NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-tWk8pe/neovim-0.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-tWk8pe/neovim-0.3.4/build/config -I/build/neovim-tWk8pe/neovim-0.3.4/src -I/usr/include -I/build/neovim-tWk8pe/neovim-0.3.4/build/src/nvim/auto -I/build/neovim-tWk8pe/neovim-0.3.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Issue Description

I guess it is a simple issue, but when I open a .json file in nvim, a good part of the text appears highlighted, like in the following screenshots:

![Screenshot from 2019-11-27 16-01-37](https://user-images.githubusercontent.com/9384697/69752079-3e06f580-112f-11ea-907a-03fcfea78c20.png)

**Comment by joshdick** [comment]
I believe this is happening because that text is valid JavaScript but not valid JSON.

`onedark.vim` is not aware of/does not have highlighting for this situation; the highlighting is probably coming from `elzr/vim-json` (possibly inherited through `/sheerun/vim-polyglot` if you're using that.)

You can work around this by renaming your file to have a `.js` extension, or if that's not possible, adding the line `/* vim: set filetype=javascript : */` to the top of the file.
