### ISSUE TITLE
Odd highlights in neovim floating window

### ISSUE THREAD

**Issue by ckipp01** [joshdick/onedark.vim#197]
I've been trying to figure this out for a while to no avail. When using `coc.nvim`'s hover feature with Neovim, there is odd highlighting that shows up. I've included a couple snapshots below to illustrate what I'm talking about. One is in a Typescript project and the other in a Scala project.

<img width="442" alt="Screenshot 2020-01-13 at 10 29 07" src="https://user-images.githubusercontent.com/13974112/72245174-3bcdfd00-35f0-11ea-9488-d2179d60d38f.png">

<img width="417" alt="Screenshot 2020-01-13 at 10 29 45" src="https://user-images.githubusercontent.com/13974112/72245178-3e305700-35f0-11ea-8952-6c43065d7c0e.png">

There has been a couple issues logged in `coc.nvim` about it, but it seems that no one can figure out how to fix it. Here is an example https://github.com/neoclide/coc.nvim/issues/1248#issuecomment-569233302. It seems to be some highlight group that isn't correctly being colored, but I've tried debugging with scriptease and even reached out to nvim, but wasn't able to figure out what highlight group it was. https://github.com/neovim/neovim/issues/11585#event-2903269713

This isn't a onedark issue really, but one that seems to be happening on a lot of themes. I just use ondark, and figured it may be worth a shot to see if someone that does themes can figure out why this is happening and provide some insight on how to fix it.

The relevant code that creates it can be found here https://github.com/neoclide/coc.nvim/blob/dc888b4a6e1e3c70049c41d1edda06c76b853983/src/model/floatFactory.ts#L192

### Terminal Emulator Info
iTerm2

### Output From `vim --version`
```
NVIM v0.5.0-fa9b057
```

Thanks a ton for such a great theme 👍

**Comment by joshdick** [comment]
I'm actually not able to reproduce this; the parenthesis that are incorrectly highlighted in your screenshot are correctly highlighted for me.

I am also using Neovim + iTerm2, but one difference between our environments is that I'm using Neovim 0.4.3 and you're using a 0.5.0 prerelease; I'm curious if you can also reproduce this with Neovim 0.4.3?

**Comment by ckipp01** [comment]
I'm at a total loss. Yea, I used to have it before as well, but for good measure, I just tried again with 0.4.3, and I still have the issue. I've removed all other plugins and stripped all my settings to only include the theme and `coc.nvim`, and I still get the same thing.

**Comment by joshdick** [comment]
Can you link to your minimal reproduction configuration?

**Comment by ckipp01** [comment]
Sure, this is what my mini `.vimrc` looks like.

```vim
set nocompatible

set runtimepath^=/Users/ckipp/.vim/plugged/coc.nvim,/Users/ckipp/.vim/plugged/onedark.vim
filetype plugin indent on
syntax on
set hidden

set termguicolors
colorscheme onedark

nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
```

**Comment by joshdick** [comment]
That was helpful! It let me reproduce the issue, and it helped me figure out the root cause along with a workaround (from my own config, which is why I couldn't originally reproduce the issue.)

First, the workaround. Add the following to your configuration, **before the `colorscheme onedark` line**:

```vim
" onedark.vim override: Don't set a background color when running in a terminal;
" just use the terminal's background color
if (has("autocmd") && !has("gui_running"))
	augroup colors
		autocmd!
		let s:white = { "gui": "#ABB2BF", "cterm": "145", "cterm16": "7"}
		autocmd ColorScheme * call onedark#set_highlight("Normal", { "fg": s:white }) "No `bg` setting
	augroup END
endif
```

The root cause seems to be that Coc is using the background color of the `Normal` highlight group when drawing the floating window, but only for those parenthesis for some reason. Removing the background color causes it to draw correctly.

**Comment by ckipp01** [comment]
YES! That does fix it!!!! Thank you so much! You have no idea how much this was bugging me, and even more so that I couldn't figure it out. I also really appreciate the explanation.

From the coc side of things. If they just removed the `Normal` highlight group, would the issue go away?

**Comment by joshdick** [comment]
Glad that fixed it, and you're welcome!

I don't know why Coc is using that particular highlight group when drawing the floating window, but yes, the issue would go away if Coc didn't use a background color when drawing those characters.

I've updated both issues you linked above with this information for those who might happen upon them in the future.

**Comment by ckipp01** [comment]
Awesome. Again, I really appreciate it. Hopefully this will help others as well since I've seen this pop up in multiple places.
