### ISSUE TITLE
PowerShell syntax highlighting is wacked

### ISSUE THREAD

**Issue by Skarlso** [joshdick/onedark.vim#2]
Hi! 

First off, awesome theme, nicely done!

Second, once I enable this, sadly, my PowerShell syntax highlighting is completely gone. It just displays it as plain text. Other custom themes are also gone, like Dockerfile and Go. I suspect because on the first line, you are resetting syntax. 

Can we do something about that? Can I somehow override for certain filetypes? What's the best way of solving this?

Cheers,
Gergely.

**Comment by Skarlso** [comment]
Got it to work. My problem was, that I had syntax on and colour defined in my vimrc file in the Plugin section of Vundle. :) Which is bad... Moved it out from there, and everything works fine.

**Comment by joshdick** [comment]
Glad you like the theme and that you figured out the issue!

**Comment by Skarlso** [comment]
Cheers dude. :) 

Yeah it's gorgeous!
