### ISSUE TITLE
Could you create a  kitty term theme please?

### ISSUE THREAD

**Issue by dagadbm** [joshdick/onedark.vim#200]
Would be nice since kitty is also well used (probably more than allacrity)

**Comment by dagadbm** [comment]
```
# Adapted from https://raw.githubusercontent.com/joshdick/onedark.vim/master/term/One%20Dark.Xresources

# Cursor
cursor			#abb2bf

# Colors
foreground		#abb2bf
background		#282c34
selection_foreground	#282c34
selection_background	#abb2bf

# black
color0:			#282c34
color8:			#3e4452

# red
color1:			#e06c75
color9:			#be5046

# green
color2:			#98c379
color10			#98c379

# yellow
color3:			#e5c07b
color11:		#d19a66

# blue
color4:			#61afef
color12:		#61afef

# magenta
color5:			#c678dd
color13:		#c678dd

# cyan
color6:			#56b6c2
color14:		#56b6c2

# white
color7:			#abb2bf
color15:		#5c6370
```

i did this but the magenta is looking really weird.. I have no idea why.. because the magenta on allacrity which is the same as this one looks fine...

**Comment by dagadbm** [comment]
the above code works. perfectly on kitty.

**Comment by joshdick** [comment]
I re-implemented this using onedark.vim's built-in theme system in #201, and fixed an error with the cyan color definition in your snippet above `color6` somehow incorrectly became `color7`.)

Let me know if the new theme works as expected for you!

**Comment by dagadbm** [comment]
damn looks SLICK!!!

even better than my attempt specially the foreground stuff.

btw you should make it clearer on your readme you support these terminals. it was not clear for me this color scheme was also done for iterm xresources allacrity and now kitty

**Comment by joshdick** [comment]
@dagadbm Glad you like it!

The README does currently say:

> The canonical version of the 16-color palette is an Xresources file located in this repository at term/One Dark.Xresources. Color schemes for various terminal emulators are also provided in `term/`.

I do agree that it's easy to miss, but if I list all of the supported terminal emulators, the README would be even longer and it's already pretty long as it is. 😆

**Comment by dagadbm** [comment]
i actually had no ide what xresources even meant before this :D 
do you have some reading stuff i can do to learn more about that?
in particular: what is ncurses how does the terminal interface with the shell (for example why do i need the termino xterm-kitty to be set on my tmux for it to work properly with kitty, how is the communication done etc.

It is something I have 0 knowledge could you point me in the right direction on this?

**Comment by joshdick** [comment]
@dagadbm `man terminfo` and `man 7 term` are great places to start!
