### ISSUE TITLE
"Pastel Like" colors with 'termcolors=16' with nvim + urxvt

### ISSUE THREAD

**Issue by sganon** [joshdick/onedark.vim#202]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

rxvt-unicode (urxvt) v9.22 - released: 2016-01-23

### Output From `vim --version`

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Issue Description
I've set my `.Xressources` to use onedark first with urxvt. The colors palette is good in the terminal so I assume the Xressources is configured correctly.

I've managed to have one dark working `let g:onedark_termcolors=256` but as you say in the README.md colors are darker than they should be.

With `g:onedark_termcolors=16` I've got something like this:
![2020-01-21-220910_1717x959_scrot](https://user-images.githubusercontent.com/15366291/72844054-0d10f000-3c9c-11ea-9222-1180825dfb03.png)

My term look like this with Xressources:
![2020-01-21-222044_1249x85_scrot](https://user-images.githubusercontent.com/15366291/72844199-52cdb880-3c9c-11ea-9d50-53d463145069.png)

Sorry if I've missed linked issue but I'm not sure what to look for and my research did not helped me.

Thanks in advance.

**Comment by joshdick** [comment]
This was almost certainly caused by #201.

Does `urxvt` support an independent background color, for example as appears in https://github.com/joshdick/onedark.vim/blob/master/term/One%20Dark.Xresources#L3?

**Comment by sganon** [comment]
Yes there I've set it to the same as the theme:
`URxvt.background:                 [100]#282C34`

How should I tweak the backgorund property then ?

**Comment by sganon** [comment]
I've reverted to https://github.com/joshdick/onedark.vim/commit/6a98de099dab7d1890dd8732db50dba87f0ee79b
(commit juste before PR #201) and the bug still exists, so maybe not this PR.

**Comment by joshdick** [comment]
Can you paste both your `.vimrc` and your `.Xresources`?

**Comment by sganon** [comment]
My `.Xressource`
```
!! Xft.dpi:       92
Xft.antialias: true
Xft.hinting:   true
Xft.rgba:      rgb
Xft.autohint:  false
Xft.hintstyle: hintslight
Xft.lcdfilter: lcddefault

XTerm*background:        #282C34
XTerm*foreground:        #ABB2BF
XTerm*pointerColor:      #ABB2BF
XTerm*faceName:          Fixed
XTerm*faceSize:          11
XTerm*reverseVideo:      on
XTerm*selectToClipboard: true

*.background:                      #282C34
*.foreground:                      #ABB2BF
*fading:                          8
*fadeColor:                       black
*.cursorColor:                     #ABB2BF
*pointerColorBackground:          #2B2C2B
*pointerColorForeground:          #16A085

!! black dark/light
*.color0:                          #5C6370
*.color8:                          #4B5263

!! red dark/light
*.color1:                          #E06C75
*.color9:                          #BE5046

!! green dark/light
*.color2:                          #98C379
*.color10:                         #98C379

!! yellow dark/light
*.color3:                          #E5C07B
*.color11:                         #D19A66

!! blue dark/light
*.color4:                          #61AFEF
*.color12:                         #61AFEF

!! magenta dark/light
*.color5:                          #C678DD
*.color13:                         #C678DD

!! cyan dark/light
*.color6:                          #56B6C2
*.color14:                         #56B6C2

!! white dark/light
*.color7:                          #ABB2BF
*.color15:                         #3E4452

Xcursor.theme: xcursor-breeze
Xcursor.size:                     0

!!URxvt.font:                       xft:Consolas:size=8,xft:Inconsolata for Powerline
URxvt.font:                         xft:JetBrains Mono:size=8:antialias=true,xft:Iosevka Term:style=Light:size=8:antialias=true:hinting=true

! alternative font settings with 'terminus':
! URxvt.font:      -xos4-terminus-medium-r-normal--16-160-72-72-c-80-iso10646-1
! URxvt.bold.font: -xos4-terminus-bold-r-normal--16-160-72-72-c-80-iso10646-1
!! terminus names see end of file!

URxvt.depth:                      32
URxvt.background:                 [100]#282C34
URxvt*scrollBar:                  false
URxvt*mouseWheelScrollPage:       false
URxvt*cursorBlink:                true
URxvt*background:                 black
URxvt*foreground:                 grey
URxvt*saveLines:                  5000

! for 'fake' transparency (without Compton) uncomment the following three lines
! URxvt*inheritPixmap:            true
! URxvt*transparent:              true
! URxvt*shading:                  138

... Ther is more conf but not related to colors
```

For my vim config, is quite splitted so here is my repos with my conf:
https://github.com/sganon/my-dot-files/tree/master/vim

**Comment by sganon** [comment]
Well it seems only urxvt related but I haven't found any clue.
I will switch to a more modern terminal ^^.

Closing the issue, thanks for your help. :)

**Comment by joshdick** [comment]
No worries!

I wasn't able to reproduce locally with your `~/.Xresources`, so one of these may have been the issue during your experiments:

* If you had tried enabling `set termguicolors`, it may have caused issues with urxvt since it doesn't seem like urxvt has 24-bit color support
* Your urxvt config should have let you use `g:onedark_termcolors=16` in your Vim config, but your current config has `g:onedark_termcolors=256`, which also may have caused the behavior you saw

You should have better luck using `set termguicolors` inside a more modern terminal, like you mentioned! 🙂

**Comment by mroavi** [comment]
I'm having the same issue described here.
I am using xterm in Ubuntu 18.04.

I included this in my `.Xresources` file: 
![image](https://user-images.githubusercontent.com/19517248/77123031-592fa500-6a3f-11ea-88f0-b90347f438ef.png)

And thisis how I setup my `.vimrc`
![image](https://user-images.githubusercontent.com/19517248/77123248-e4109f80-6a3f-11ea-8535-180ad4c75dcb.png)

Any idea what might be going wrong?
