### ISSUE TITLE
My lightline doesn't have the "arrow like design" is there some kind of specific font I need to download?

### ISSUE THREAD

**Issue by Aayush9029** [joshdick/onedark.vim#204]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

Terminal emulator(s) and their version(s) used, if applicable: `Replace this text if applicable; otherwise delete this section`

### Output From `vim --version`

```
Replace this text with the output
```

### Issue Description

Write your issue description here.

**Comment by joshdick** [comment]
You need a [Powerline Font](https://github.com/powerline/fonts) for this to work as expected.

[Input Mono](https://input.fontbureau.com/) is a font that should work, that is free for private use.
