### ISSUE TITLE
Is it possible to change the background color?

### ISSUE THREAD

**Issue by mrillusi0n** [joshdick/onedark.vim#207]
I'd like to be able to do something like `let g:onedark_bg = 'darkest'`.

**Comment by joshdick** [comment]
It's definitely possible, check out the examples here: https://github.com/joshdick/onedark.vim#onedarkextend_highlight

**Comment by mrillusi0n** [comment]
Thank you, but I found it difficult to tweak around.

I use the Cool Retro Terminal.

![image](https://user-images.githubusercontent.com/37063502/74265105-e4729800-4d27-11ea-961b-a612a18c50f0.png)

After setting `highlight Normal ctermbg=black`. I got what I wanted.

![image](https://user-images.githubusercontent.com/37063502/74265251-39aea980-4d28-11ea-90ea-c699f3f3fde7.png)

**Comment by joshdick** [comment]
Glad you figured out a solution!
