### ISSUE TITLE
Errors on setting colorscheme to onedark in Gvim 8.2

### ISSUE THREAD

**Issue by bobf32** [joshdick/onedark.vim#213]
Win 10 / Vim 8.2

Many errors encountered setting colour scheme to onedark. Same operation in 8.1 gives no errors. 

Sorry not to include errors in bug report but I've been battling this for ages and having rolled back to 8.1 I can't face installing 8.2 again. 

Not expecting any this ticket to receive much attention because of this, more of a heads up ;)

**Comment by joshdick** [comment]
What kind of errors? CLI Vim 8.2 loads the theme with no issues, so I'm curious as to what errors you were seeing in GVim.

**Comment by bobf32** [comment]
Hopefully this is more help. I have installed 8.2 portable version so as not to affect my 8.1 instance which is OK. If I try and open portable gVim 8.2 using my regular _vimrc (which calls "colo onedark") no window actually appears. Running with the --startuptime argument results in a truncated log file (see attachment 1).

If I start 8.2 gVim having commented out my _vimrc line that calls "colo onedark" the Vim window does appear OK. If I then do "colo onedark" I get the errors in the second attachment (first page of errors only shown, there are lots more).

Hope that helps.

![1  2020-02-26 09_29_16-startuptime vim (~) - GVIM](https://user-images.githubusercontent.com/6544564/75331790-3b758280-587b-11ea-8fa8-523cc366f250.png)
![2  2020-02-26 09_33_34-Calendar - Andrew Gabelli@thomsonreuters com - Outlook](https://user-images.githubusercontent.com/6544564/75331793-3c0e1900-587b-11ea-8cae-fe43e38884c3.png)

**Comment by joshdick** [comment]
Looks like you might be running an old version of the colorscheme, this seems to be the same problem as #148 and was fixed in 04ba47974e4a468e0c1ad32d867594ffc63c159c. Does updating your copy make a difference?

**Comment by bobf32** [comment]
D'oh. Yes, a big one. Thanks ;)

**Comment by joshdick** [comment]
Glad it was an easy fix! 🙂
