### ISSUE TITLE
Swap airline colors

### ISSUE THREAD

**Issue by ChristianChiarulli** [joshdick/onedark.vim#217]
Is there an easy way to swap the colors for normal and insert mode for instance, for just the airline without overriding all colors?

**Comment by joshdick** [comment]
`onedark.vim` doesn't expose an explicit way to do this, but you can edit the file ` onedark.vim/autoload/airline/themes/onedark.vim` and swap the values (after the equals sign) of the `let s:N1` (normal mode) and `let s:I1` (inert mode) definitions to achieve the effect you want.
