### ISSUE TITLE
onedark#extend_highlight() breaks Airline theme

### ISSUE THREAD

**Issue by baco** [joshdick/onedark.vim#220]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Output From `vim --version`

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 12 2020 02:37:13)
Included patches: 1-716
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-RuXSEA/vim-8.2.0716=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo  -lselinux -lcanberra -lacl -lattr -lgpm -ldl
```
```
NVIM v0.5.0-504-g55b62a937
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-c5e1e25b-f5b7-4e61-bd02-89fb2bc09256

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Issue Description

When configuring Vim/Neovim to change `Normal` background like this:
```
autocmd ColorScheme onedark silent!
	\ call onedark#extend_highlight('Normal', {'bg': {'gui': 'NONE'}})
```
it affects further uses of color black defined in the colors dictionary (`s:colors.black.gui`). This behavior makes other plugins like Airline to have some colors failing because `s:colors.black.gui` is `'NONE'`, making that the mode-indicator (NORMAL, INSERT, VISUAL) on Airline bar to have a very difficult to read transparent color for foreground color.

**Comment by AndysonDK** [comment]
What exactly does this line do: `onedark#extend_highlight('Normal', {'bg': {'gui': 'NONE'}})`
Remove the background color so the terminal's color will show instead?

**Comment by baco** [comment]
Exactly! And adding the fact that the terminal can have transparent background, then Vim/Neovim can benefit from that too.

The issue is that Airline uses that color for a foreground color (the text), and having the text color transparent can end in a color (depending on the background color) that is unreadable.

Perhaps, Airline foreground color should be a forced back or any color, but don't copy the Vim theme's background color.

**Comment by AndysonDK** [comment]
Hmmm it's weird because I can't get to work at all. I can't remove the background for some reason here is my issue for reference:
https://github.com/joshdick/onedark.vim/issues/235

**Comment by baco** [comment]
I achieve it like this on my Vimrc file: https://gitlab.com/baco/dotconf/-/blob/master/vim/vimrc#L56-62
