### ISSUE TITLE
Control string highlight in C is showing a weird behaviour.

### ISSUE THREAD

**Issue by mrillusi0n** [joshdick/onedark.vim#222]
When I launch, `%d` is not highlighted.
![image](https://user-images.githubusercontent.com/37063502/83877316-f30e1080-a757-11ea-8b81-f2db57597cf1.png)

But after I switch the colorscheme to `jellybeans` and back, `%d` is highlighted in red. It happens only when I switch back from `jellybeans`, not with any other from my list of schemes.
![image](https://user-images.githubusercontent.com/37063502/83877306-ee495c80-a757-11ea-8648-23ce4b083f57.png)

**Comment by kostiskalkounos** [comment]
I would love it if you could implement this, your theme is my favourite one. Other colour schemes, like solarized,  colorise '\n' as well. The following screenshot showcases a cpp piece of code using the rakr/vim-one theme.

<img width="500" alt="Screenshot 2020-09-25 at 16 53 20" src="https://user-images.githubusercontent.com/27889580/94275541-c3c22000-ff4f-11ea-8e99-9eb9a1c8024e.png">

**Comment by joshdick** [comment]
@kostiskalkounos / @mrillusi0n I merged #244 (which subsumes #237) to make special character highlighting consistent across the board, and resolves this issue.

@kostiskalkounos Thanks very much for determining the root cause of this issue, for the screenshots, and for opening #237!
