### ISSUE TITLE
Disable background color setting

### ISSUE THREAD

**Issue by Arteneko** [joshdick/onedark.vim#223]
### Terminal Emulator Info

I use kitty 0.17.4.

### Output From `vim --version`

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Issue Description

I'm trying to find a way to use this theme for syntax and foreground highlighting *only*, as I'd like to keep my background as-is (as configured in my kitty configuration).

I tried the `augroup` for airline colours and for background colour change on certain symbol types, but did not manage to completely disable it. Is there a way?

**Comment by 66RING** [comment]
try this `autocmd ColorScheme * highlight Normal ctermbg=NONE guibg=NONE`

**Comment by Arteneko** [comment]
Using this in neovim doesn't disable anything (used below the `colorscheme onedark` config rule).

**Comment by 66RING** [comment]
no idea.
I use neovim too.
It work well on Alacritty.

It that what you want?
![2020-06-29_19-59](https://user-images.githubusercontent.com/49358576/86002681-40be2600-ba43-11ea-8c05-2697273511db.png)

**Comment by Arteneko** [comment]
Indeed...

On kitty (with transparent shell, neovim being the only one to display an opaque background) myself.

**Comment by AndysonDK** [comment]
Hey, I would just like to notify you that this might be a working solution for you:
https://github.com/joshdick/onedark.vim/issues/235#issuecomment-674898568

**Comment by joshdick** [comment]
@Arteneko

> I tried the `augroup` for airline colours and for background colour change on certain symbol types, but did not manage to completely disable it.

Can you confirm whether you tried the example in the README (https://github.com/joshdick/onedark.vim#onedarkset_highlight)?

**Comment by Arteneko** [comment]
I indeed tried it (sorry for the late reply), and there's no change in behaviour.

```
if (has("autocmd") && !has("gui_running"))
        augroup colorset
                autocmd!
                let s:white = { "gui": "#ABB2BF", "cterm": 145, "cterm16": "7" }
                autocmd ColorScheme * call onedark#set_highlight("Normal", { "fg": s:white })
        augroup END
endif
```

**Comment by joshdick** [comment]
@Arteneko Apologies that I lost the thread on this.

As the README specifies, the `augroup` config must appear **before** the `colorscheme onedark` line in your Vim configuration.

Does making that adjustment resolve the issue?

**Comment by Arteneko** [comment]
Making it indeed resolves it, so thanks.

Kinda surprised that the configuration shown in the screenshot posted by 66RING above works.

**Comment by joshdick** [comment]
@Arteneko You’re welcome, I’m glad it worked!
