### ISSUE TITLE
Add spaceline statusline

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [joshdick/onedark.vim#224]
[Spaceline](https://github.com/hardcoreplayers/spaceline.vim) is the best looking statusline I've seen yet (it's designed to look like the spacemacs statusline). It has many more features than lightline and is even lighter. I've been messing around with a colorscheme but I can't make one that looks right. Would love to see what you could do!

**Comment by joshdick** [comment]
It looks like you've since added a `one` theme to Spaceline itself (https://github.com/glepnir/spaceline.vim/commits/master/autoload/spaceline/colorscheme/one.vim), so I'm going to close this issue, but feel free to keep the conversation going!
