### ISSUE TITLE
Q: vim-plug compatibility

### ISSUE THREAD

**Issue by Kreyren** [joshdick/onedark.vim#227]
- [X] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [X] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

Could this be installed through vim-plug <https://github.com/junegunn/vim-plug> somehow?

**Comment by Kreyren** [comment]
Solved, it works with `Plug 'joshdick/onedark.vim'` where i had to invoke `:PlugClean` before `:PlugInstall` for some reason~

**Comment by joshdick** [comment]
`Plug 'joshdick/onedark.vim'` should theoretically just work, have you tried it? I used do do it myself before moving away from `vim-plug`.

Look at the left of the diff: https://github.com/joshdick/dotfiles/commit/670323d7511bfa82df9753c2ee0ae1d50ec8c6e2#diff-0733a4c9dbf08123110a9bf673488998

**Comment by joshdick** [comment]
Closed just as I replied, glad it's working!

**Comment by Kreyren** [comment]
> You closed this just as I replied

Sorry! >.> I appreciate the info though ^-^

> Plug 'joshdick/onedark.vim' should theoretically just work, have you tried it?

Yep tried that including the whole url (with .vim, .vim.git, and without extension) it didn't work for me with:
![image](https://user-images.githubusercontent.com/11302521/86661526-1690d900-bfec-11ea-8c48-5988135a428e.png)

But it was resolved by `:PlugClean`

**Comment by Kreyren** [comment]
FWIW my theory is that github had a temporary shortage which seems to cause it to pull incomplete repository that might have caused it?

(it was showing unicorns on github on my end when this issue appeared)

**Comment by joshdick** [comment]
Not sure, but I’m glad it worked eventually!
