### ISSUE TITLE
javascript: option to disable coloring of dollar and braces inside of template literals 

### ISSUE THREAD

**Issue by andres-lowrie** [joshdick/onedark.vim#238]
Thanks for your work on this!, 

Could you add a way to disable the highlighting of the dollar-sign and braces inside of a Template Literals in JavaScript.

It would be nice if the dollar and the braces where the same color as the expression and not their own color.

```javascript
const foo = `this would be color 1 ${while the dollar and braces and string would be color 2}` 
```

If is this is something I can do via my rc file , could you point me in the right direction? I tried straight up disabling it with

```
hi Noise ctermfg=NONE guifg=NONE gui=NONE term=NONE
```

but that didn't work for me

**Comment by joshdick** [comment]
Do you know what JavaScript syntax file you're using? Is it the built-in one or an external one from something like [`vim-polyglot`](https://github.com/sheerun/vim-polyglot)?

Knowing which highlight group your syntax file is assigning to the dollar sign/braces would allow you to override that highlight group in your Vim configuration. Adding [this mapping](https://github.com/joshdick/dotfiles/blob/7deeba8a8f6c6c8690cb437e1b8a3c78e2c1fb66/vim.symlink/config/settings/mappings.vim#L93-L97) to your .vimrc, positioning your cursor over the dollar sign/braces in a JavaScript file, then invoking the mapping should display the relevant highlight group.

**Comment by andres-lowrie** [comment]
I'm getting this:

```
hi<jsTemplateBraces> trans<jsTemplateBraces> lo<Noise>
Press ENTER or type command to continue
```

using the following javascript https://github.com/pangloss/vim-javascript, 

let me fiddle around with the highlight command see what's what, thanks again for you help
