### ISSUE TITLE
Inconsistent backgrounding where text isn't present

### ISSUE THREAD

**Issue by wiz-h** [joshdick/onedark.vim#260]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [X] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

Windows Terminal Preview (v1.8.1032.0)

### Output From `vim --version`

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 13:19:27)
MS-Windows 32-bit console version
Compiled by mool@tororo
Huge version without GUI.  Features included (+) or not (-):
+acl               +eval              +multi_byte        -tag_old_static
+arabic            +ex_extra          +multi_lang        -tag_any_white
+autocmd           +extra_search      -mzscheme          -tcl
+autochdir         -farsi             -netbeans_intg     +termguicolors
+autoservername    +file_in_path      +num64             +terminal
-balloon_eval      +find_in_path      +packages          -termresponse
+balloon_eval_term +float             +path_extra        +textobjects
-browse            +folding           -perl              +textprop
++builtin_terms    -footer            +persistent_undo   -tgetent
+byte_offset       +gettext/dyn       +popupwin          +timers
+channel           -hangul_input      -postscript        +title
+cindent           +iconv/dyn         +printer           -toolbar
+clientserver      +insert_expand     +profile           +user_commands
+clipboard         +job               -python            +vartabs
+cmdline_compl     +jumplist          -python3           +vertsplit
+cmdline_hist      +keymap            +quickfix          +virtualedit
+cmdline_info      +lambda            +reltime           +visual
+comments          +langmap           +rightleft         +visualextra
+conceal           +libcall           -ruby              +viminfo
+cryptv            +linebreak         +scrollbind        +vreplace
+cscope            +lispindent        +signs             +vtp
+cursorbind        +listcmds          +smartindent       +wildignore
+cursorshape       +localmap          +sound             +wildmenu
+dialog_con        -lua               +spell             +windows
+diff              +menu              +startuptime       +writebackup
+digraphs          +mksession         +statusline        -xfontset
-dnd               +modify_fname      -sun_workshop      -xim
-ebcdic            +mouse             +syntax            -xpm_w32
+emacs_tags        -mouseshape        +tag_binary        -xterm_save
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND  -DFEAT_JOB_CHANNEL      -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG /arch:IA32 /Zl /MT -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_HUGE /Fd.\ObjCi386/ /Zi
Linking: link  /nologo /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:i386   libcmt.lib  user32.lib          winmm.lib WSock32.lib  /PDB:vim.pdb -debug
```

### Issue Description

When attempting to the configure `onedark` as my main theme in a fresh config I get a strange background color with the reason of perfectly reasonable text:

![WindowsTerminal_tJojrlwjax](https://user-images.githubusercontent.com/38634944/119785069-b749ea80-be83-11eb-9288-0f26a2e6edfb.png)

The black background only appears in areas when not covered by text, but still nevertheless, makes it quite difficult to read. I'm wondering if there possibly a solution to this.

I have already established that thankfully `set termguicolors` seems to work perfectly fine, capturing the colors as it should be, however commenting the other parts due to OS differences. This, unfortunately, didn't seem to be the issue either.

**One thing I have noticed is when opening gVim, the background seems to be printed perfectly, yet I don't know how to convert this into a solution.**

I have current already tried:

- [X] Changing it to 16-bit mode via `let g:onedark_termcolors=16`
- [X] Manually overwriting the color mode to 24-bit (even though it should be implied by the 256-color terminal) via `let g:onedark_termcolors=256`
- [X] Checking for plugin conflicts
- [X] Making sure there are no syntax errors (overflowing statements/breaking comments)

If there is something else that I should supply or try out, please let me know. I'm truly looking forward to be able to use this theme across multiple of my editors.

Thanks!

**Comment by joshdick** [comment]
Interesting, I hadn't tried running Windows Vim within Windows Terminal.

This appears to be an issue between Vim and Windows Terminal rather than an issue with either onedark.vim or your configuration.

I'm curious if any of the workarounds mentioned in [this Windows Terminal issue](https://github.com/microsoft/terminal/issues/832) make any difference for you?

**Comment by Sakura0134** [comment]
> Interesting, I hadn't tried running Windows Vim within Windows Terminal.
> 
> This appears to be an issue between Vim and Windows Terminal rather than an issue with either onedark.vim or your configuration.
> 
> I'm curious if any of the workarounds mentioned in [this Windows Terminal issue](https://github.com/microsoft/terminal/issues/832) make any difference for you?

It works.
