### ISSUE TITLE
Add support for gitsigns

### ISSUE THREAD

**Issue by rostero1** [joshdick/onedark.vim#272]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

OneDark can add support for gitsigns by adding the following:

```
hi link GitSignsAdd    SignifySignAdd
hi link GitSignsChange SignifySignChange
hi link GitSignsDelete SignifySignDelete
```

**Comment by joshdick** [comment]
Implemented in https://github.com/joshdick/onedark.vim/pull/274. Thanks for the suggestion!
