### ISSUE TITLE
Key not present in Dictionary: "foreground"

### ISSUE THREAD

**Issue by leesoh** [joshdick/onedark.vim#278]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

iTerm 3.4.8

### Output From `vim --version`

Neovim 0.5.0

### Issue Description

First of all, thank you for all the work you put into maintaining this excellent theme, it's a joy to behold :)

Since updating to the most recent version I am now receiving a `E716: Key not present in Dictionary: "foreground"` when launching Neovim. I've fully removed and reinstalled the plugin and have confirmed that `colors/onedark.vim` is where it needs to be.

**Comment by joshdick** [comment]
Thanks for using onedark.vim!

I know you said you've removed and reinstalled the plugin, but could there somehow be an old `autoload/onedark.vim` file lingering somewhere in your config?

How is `onedark.vim` being loaded? Can you share any relevant [Neo]vim config?

**Comment by leesoh** [comment]
That is literally the only thing I forgot to check! It was an old `autoload/onedark.vim`. Thanks so much for the help!

**Comment by joshdick** [comment]
You're welcome!
