### ISSUE TITLE
Odd highlighting in float window.

### ISSUE THREAD

**Issue by ckipp01** [joshdick/onedark.vim#279]
Hello! So I just updated onedark and it includes https://github.com/joshdick/onedark.vim/pull/271. I read through the description and briefly tried a couple things but couldn't get this to work. I also made sure to update my term colorscheme to the latest. A while back I created this https://github.com/joshdick/onedark.vim/issues/197, which was a lifesaver. I have pointed that out to countless people who always seem to get stuck on it. After the update I now have this issue again. For example:

<img width="298" alt="Screenshot 2021-07-23 at 20 40 06" src="https://user-images.githubusercontent.com/13974112/126827150-f695ab4c-f21c-4324-876c-b5b5ed2be9af.png">

This is just using the default hover that Neovim ships with when using `vim.lsp.buf.hover()`. I have this in my init file:

```lua
vim.cmd(
  [[autocmd ColorScheme * call onedark#set_highlight("Normal", { "fg": { "gui": "#ABB2BF", "cterm": "145", "cterm16" : "7" } })]]
)
```

How can I correctly mimic this with the new changes?

- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

```
iTerm2 Build 3.4.8
xterm-256color
```

### Output From `vim --version`

```
NVIM v0.6.0-dev+a8c3d50fa
```

**Comment by Sakura0134** [comment]
Yeah I am having the same issue too

**Comment by Sakura0134** [comment]
I just found a fix(From this channel) https://github.com/microsoft/terminal/issues/832#issuecomment-493747616

**Comment by ckipp01** [comment]
I was able to get this worked out. There are some issues with autocmds on the nightly of Neovim causing them to behave differently. Just needed to move some stuff around in order to get it to work.

**Comment by joshdick** [comment]
@ckipp01 I’m glad you were able to get it working!
