### ISSUE TITLE
Inconsistent hilighting when using Treesitter for keywords

### ISSUE THREAD

**Issue by baco** [joshdick/onedark.vim#280]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

Terminal emulator(s) and their version(s) used, if applicable: Kitty Terminal, Tilix and [Neovim-GTK](https://github.com/daa84/neovim-gtk)

### Output From `vim --version`

```
NVIM v0.6.0-dev+105-g8baf7bce2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az87-30

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Issue Description

When turning on Treesitter's syntax highlighting Python's statements (pythonStatement) are interpreted as Keywords, and since pythonStatement is set to purple and Keywords are set to red the onedark theme gets a rather drastic change:

This is the theme normally without Treesiter's highlighting:
![image](https://user-images.githubusercontent.com/102958/128605255-74142978-3e0d-49c5-9c8a-6441909b9045.png)

After turning on Treesitter's highlighting
![image](https://user-images.githubusercontent.com/102958/128605268-34caafc1-c11f-43eb-9114-527f0c1cfd07.png)

it drastically affects every keyword: `def`, `class`, `return`, `if`, `for`, `while`, among others.

**Comment by ArtAndreev** [comment]
I have the same problem with `coc.nvim` syntax highlighting when `semanticTokens.enable` is `true` in `coc-settings.json`. The fix in linked PR fixes the problem.

The VSCode analogue doesn't have this problem.

May I ask you to merge the PR? @joshdick

**Comment by joshdick** [comment]
@ArtAndreev / @baco I merged this fix just now, thank you!
