### ISSUE TITLE
onedark_color_overrides not taking effect

### ISSUE THREAD

**Issue by dstadelm** [joshdick/onedark.vim#284]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info
Gnome Terminal

### Output From `vim --version`

```
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az242-526

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

```

### Issue Description
onedark_color_overrides are not working

with the following configuration I expect a darker background (TUI 256)
```
" settings for one dark (instead of one half dark)
call minpac#add('joshdick/onedark.vim',  {'type': 'opt'})
set termguicolors
let g:one_allow_italics = 1
let g:onedark_terminal_italics = 1
let g:lightline = {
  \ 'colorscheme': 'onedark',
  \}
let g:onedark_color_overrides = {
  \  "black" : { "gui" : "#1e2127", "cterm" : 235, "cterm16" : 0 }
  \}
packadd onedark.vim
colorscheme onedark
```

But no matter what values I set the background does not change.

It used to work until I recently updated the package.

**Comment by joshdick** [comment]
@dstadelm Thanks for using onedark.vim! I apologize that [these changes](https://github.com/joshdick/onedark.vim/pull/271) likely broke your configuration.

There might be a simple fix, though: does overriding `"background"` instead of `"black"` get things working again?

**Comment by dstadelm** [comment]
Hi @joshdick 
Thanks for the fast reply and apologies for my belated reply. 
Yes indeed this fixed the issue!

**Comment by joshdick** [comment]
@dstadelm No worries, glad to hear it, and thanks for using onedark.vim!

**Comment by mikehaertl** [comment]
@joshdick I had the same problem. Shouldn't this also be fixed in the README?

**Comment by joshdick** [comment]
@mikehaertl Fixed in https://github.com/joshdick/onedark.vim/pull/291, thanks for the suggestion!
