### ISSUE TITLE
Changing background color from vimrc

### ISSUE THREAD

**Issue by shivanshu-semwal** [joshdick/onedark.vim#285]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [ ] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

Terminal emulator(s) and their version(s) used, if applicable: `alacritty`

### Output From `vim --version`

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)
```

### Issue Description

```
colorscheme onedark
if exists('+termguicolors')
  let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif
```

I put this in `vimrc`, then the color scheme work, now i want to remove the bg so as to match the my teminal bg color, 
I do this `hi Normal ctermbg=NONE`, but this don't work, so I change the file `autoload/onedark.vim` as follows: 
```
\ "background": get(s:overrides, "background", { "gui": "#1e2127", "cterm": "235", "cterm16": "NONE" }),
```
Is there some way to do that in `vimrc` instead ?

**Comment by joshdick** [comment]
@shivanshu-semwal Thanks for using onedark.vim! [This example in the README](https://github.com/joshdick/onedark.vim#onedarkset_highlight) should do exactly what you're asking.

**Comment by shivanshu-semwal** [comment]
Thanks that worked.
