### ISSUE TITLE
Error during installation: `Key not present in Dictionary: "visual_black "`

### ISSUE THREAD

**Issue by kohane27** [joshdick/onedark.vim#292]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

alacritty 0.10.0-dev (ec4dc326)

`Alacritty` supports TRUECOLOR.

### Output From `nvim --version`

```
NVIM v0.5.0
Build type: Debug
LuaJIT 2.1.0-beta3
```

### Issue Description

Steps to reproduce:

1. Install through the plugin manager `vim-plug`:
```
call plug#begin(has('nvim') ? stdpath('data') . '/plugged' : '~/.vim/plugged')
    Plug 'joshdick/onedark.vim'
call plug#end()
```
2. Add the following two lines to `/home/user/init.vim`:

```
set background=dark
colorscheme onedark
```
3. Restart neovim and the following appears:

```
Error detected while processing /home/user/.config/nvim/colors/onedark.vim:
line  122:
E716: Key not present in Dictionary: "visual_black " Black out selected text in 16-color visual mode"
E15: Invalid expression: s:colors.visual_black " Black out selected text in 16-color visual mode
line  221:
E121: Undefined variable: s:visual_black
E116: Invalid arguments for function <SNR>16_h
```

Any help is much appreciated. Thank you:)

**Comment by yabcd** [comment]
I have the same problem because there is no color configuration for visual_black in autoload /onedark.vim, you can do it yourself. I chose to delete the fg property on line 221 in the error file.

**Comment by joshdick** [comment]
All references to `visual_black` were removed in #271, around ~5 months before this writing.

The issue is likely either that `autoload/onedark.vim` is out of date, in which case you should re-clone or update your copy of onedark.vim, or that `visual_black` is still being referenced in your own configuration, in which case it should be removed from your configuration.

**Comment by kohane27** [comment]
- The reason it wasn't working is that in my `nvim` dir I have a dir called `colors` with `onedark.vim` inside. Once I deleted it, I could use `joshdick/onedark.vim`. Sorry for my mistake.

**Comment by briantully** [comment]
FWIW, I experienced this issue because I also had 'flazz/vim-colorschemes' installed, which apparently includes an older version of onedark.vim that has this issue. Removing or renaming onedark.vim within vim-colorschemes/colors fixed the issue for me.
