### ISSUE TITLE
Highlight Undercurls

### ISSUE THREAD

**Issue by captainko** [joshdick/onedark.vim#296]
![image](https://user-images.githubusercontent.com/32269291/156951595-689691dc-2e01-4d59-b4eb-03cf86a2ee4b.png)

**Comment by joshdick** [comment]
I'm not sure what the issue is, the underline groups are being rendered with underlines. Are you asking for underlines to be rendered as undercurls instead?

Also, I'm curious what plugin you're using to search across highlights?

**Comment by captainko** [comment]
Sorry for not making it clear enough. I think the color for the underline should be linked to the corresponding diagnostic. 
Ex:  `DiagnosticUnderlineHint`  -> `DiagnosticHint`

**Comment by captainko** [comment]
I use Telescope builtin functions to search through hightlights.
