### ISSUE TITLE
Error when starting vim

### ISSUE THREAD

**Issue by gblock0** [joshdick/onedark.vim#3]
I'm getting the following error when starting Macvim and using this color scheme.
<img width="823" alt="screen shot 2015-11-25 at 9 36 10 am" src="https://cloud.githubusercontent.com/assets/1434705/11399911/370f61b2-9358-11e5-9938-495d4730cdc0.png">

I get the same error when trying use it in Neovim (just different line numbers)
<img width="804" alt="screen shot 2015-11-25 at 9 35 48 am" src="https://cloud.githubusercontent.com/assets/1434705/11399941/5d9b9b52-9358-11e5-89c1-0f6dd649047e.png">

I do not get these errors with other color schemes.

It seems to load fine after I hit enter, it's just annoying to get them every time I open vim.

**Comment by joshdick** [comment]
Odd, I don't use Neovim, but I do not see those errors in MacVim 7.4 (84).

Are you loading multiple themes by accident? Which version(s) of Neovim/MacVim are you using?

**Comment by gblock0** [comment]
Sorry just have posted that.

Macvim:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 18 2015 15:00:37)
MacOS X (unix) version
Included patches: 1-922
Compiled by Homebrew
```

Neovim:
```
NVIM 0.1.0 (compiled Nov  1 2015 16:15:29)
Commit: v0.1.0
Build type: RelWithDebInfo
```


I don't think I am loading two themes.

**Comment by joshdick** [comment]
I found your [dotfiles repo](https://github.com/gblock0/dotfiles) and saw that you use [quick-scope](https://github.com/unblevable/quick-scope), which looks like it could be conflicting with my theme somehow. Can you try temporarily disabling the plugin to see if the errors vanish?

**Comment by gblock0** [comment]
That seems to be it. What made quick-scope stand out to you?

Thanks!

**Comment by joshdick** [comment]
I Googled for `set_highlight_colors`, which is a function name that appeared in the errors you showed but isn't defined anywhere in my theme. quick-scope showed up in the results. I then looked for your dotfiles and saw that you were using that plugin, and put two and two together :)

I don't have time to see where the conflict is now, but will look soon.

**Comment by gblock0** [comment]
Gotcha haha. Well thanks for finding that. 




If I have some time this weekend I will try to take a look as well.


--
Gregory Block
gblock0@gmail.com
773-391-7439

**Comment by joshdick** [comment]
It looks like the theme now works properly with quick-scope as of e777901.
