### ISSUE TITLE
Conflict with itchyny/vim-cursorword

### ISSUE THREAD

**Issue by 416207298** [joshdick/onedark.vim#303]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info
```
Window terminal
```

### Output From `vim --version`

```
vim  8.2.5105
```

### Issue Description
When switching to another file using Nerdtree or LeaderF, the effect of vim-cursorword is disappeared. It only worked when first opening a file.

**Comment by joshdick** [comment]
Do you have this issue with any other colorschemes? Have you tried loading vim-cursorword after onedark.vim in your Vim configuration?

**Comment by 416207298** [comment]
Yes. Recently I use gruvbox and I found it has the same issue. I don't know why.

**Comment by joshdick** [comment]
It might be worth reopening the bug you opened and then closed on `itchyny/vim-cursorword` related to this issue, with the additional context about also seeing this issue with gruvbox: https://github.com/itchyny/vim-cursorword/issues/32

As far as I can tell, this is not a problem with onedark.vim, so I'm going to close this issue, but feel free to keep the conversation going!
