### ISSUE TITLE
Add CocMenuSel

### ISSUE THREAD

**Issue by rtucek** [joshdick/onedark.vim#313]
Recently, COC has started using its own popup implementation for making suggestions. Refer to [this PR](https://github.com/neoclide/coc.nvim/pull/3862).
In particular, the maintainer has introduced `CocMenuSel` for highlighting the current selection in the popup. Apparently, this caused some [disruption with colorschemes](https://github.com/neoclide/coc.nvim/issues/3980) in general.

Right now, with Onedark's color scheme, scrolling through the popup's suggestion with `<C-N>` or `<C-P>` does not show a proper indicator of the current position.
As a workaround, I've started linking `CocMenuSel` with `PmenuSel`, in [my .vimrc](https://github.com/rtucek/dotfiles/commit/5480bdd7840e62ec3bf51a5c63363d04616402f3)... it's not ideal, but it works :smile: 

Would you consider adding first-level support for `CocMenuSel`?

Most importantly, thank you for the great color scheme! I'm using it for the last 3 years!

**Comment by joshdick** [comment]
@rtucek Thanks for the detailed report! The workaround you mentioned is ideal enough for me 🙂, so I added it to onedark.vim in #316.
