### ISSUE TITLE
Warning sign from ALE has wrong color

### ISSUE THREAD

**Issue by ArtAndreev** [joshdick/onedark.vim#318]
Warning sign in sign column has default color from todo highlighting. It's purple. The warning message has yellow highlighting. I suggest to color it in yellow.

Now:

<img width="175" alt="изображение" src="https://user-images.githubusercontent.com/26388769/194775245-ec46cfb4-3be1-4a17-b777-553cb3ffb224.png">

I've created a PR https://github.com/joshdick/onedark.vim/pull/317.

After this fix the sign has a matching color:

<img width="189" alt="изображение" src="https://user-images.githubusercontent.com/26388769/194775291-241e35b3-fd10-442a-9925-13f59f72e3e2.png">

**Comment by joshdick** [comment]
Fixed by #317. Thanks for the report and the PR!
