### ISSUE TITLE
Make autocomplete more obvious

### ISSUE THREAD

**Issue by simonsmith** [joshdick/onedark.vim#32]
I run into this problem a few times:

<img width="452" alt="screen shot 2016-05-11 at 23 36 41" src="https://cloud.githubusercontent.com/assets/360703/15198744/535ef5aa-17d1-11e6-978a-1fb3e130c0d1.png">

It's hard to tell at first glance where my code and the autocomplete end. Atom gets round this with a drop shadow. Maybe a slightly lighter shade could be used on the autocomplete background?

**Comment by simonsmith** [comment]
Sorry about that! Looks great though 👍

**Comment by joshdick** [comment]
No worries, it's my fault! :stuck_out_tongue_closed_eyes:
