### ISSUE TITLE
Abunch of errors

### ISSUE THREAD

**Issue by ItsCheesy** [joshdick/onedark.vim#326]
I moved the colors .vim into the colors directory, restarted gvim and i tried to set the color scheme to onedark and i got a bunch of errors saying getColors was not a function

**Comment by joshdick** [comment]
Please double check that you followed [step 1 of the installation instructions](https://github.com/joshdick/onedark.vim#installation) correctly -- seems like you might not have copied `autoload/onedark.vim` to `~/.vim/autoload/`.
