### ISSUE TITLE
Neovim terminal colours

### ISSUE THREAD

**Issue by simonsmith** [joshdick/onedark.vim#36]
Might be a nice touch to add support for the built in terminal in neovim. As seen here - https://github.com/chriskempson/base16-builder/pull/346

**Comment by joshdick** [comment]
Good call, noticed this issue today myself!

**Comment by dkarter** [comment]
@joshdick any progress on that? we could use something like:

```vim
let g:terminal_color_0  = '#2e3436'
let g:terminal_color_1  = '#cc0000'
let g:terminal_color_2  = '#4e9a06'
let g:terminal_color_3  = '#c4a000'
let g:terminal_color_4  = '#3465a4'
let g:terminal_color_5  = '#75507b'
let g:terminal_color_6  = '#0b939b'
let g:terminal_color_7  = '#d3d7cf'
let g:terminal_color_8  = '#555753'
let g:terminal_color_9  = '#ef2929'
let g:terminal_color_10 = '#8ae234'
let g:terminal_color_11 = '#fce94f'
let g:terminal_color_12 = '#729fcf'
let g:terminal_color_13 = '#ad7fa8'
let g:terminal_color_14 = '#00f5e9'
let g:terminal_color_15 = '#eeeeec'
```

Numbers probably matching https://jonasjacek.github.io/colors/

but replace the colors with the colors relevant to this theme. - this will probably not provide full support but it's a good start. Any thoughts?
