### ISSUE TITLE
Neovim colors off inside tmux

### ISSUE THREAD

**Issue by scwood** [joshdick/onedark.vim#39]
<img width="1440" alt="screen shot 2016-06-05 at 1 44 58 am" src="https://cloud.githubusercontent.com/assets/9126138/15804024/4cfdf3f4-2abf-11e6-9480-21b6d1904e26.png">

The tmux block in the README doesn't help things. Using minimal configs for both.

```
$ brew info tmux
tmux: stable 2.2 (bottled), HEAD
```

```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 27 2016 20:19:09)
```

**Comment by simonsmith** [comment]
Do you have true colour enabled in neovim and tmux? 

I have something like:

```
if has('nvim')
  let $NVIM_TUI_ENABLE_TRUE_COLOR = 1
endif

" Theme
if !has('nvim')
  let g:onedark_termcolors=16
endif
set background=dark
silent! colorscheme onedark
```

Also follow [this guide](http://sunaku.github.io/tmux-24bit-color.html#usage) for tmux true colour
