### ISSUE TITLE
It seems the colors and background dosen't like the example screenshot

### ISSUE THREAD

**Issue by joenil** [joshdick/onedark.vim#40]
![image](https://cloud.githubusercontent.com/assets/11400674/16177761/97ea6726-3668-11e6-9b44-93e925a7bdd3.png)

**Comment by joenil** [comment]
`
syntax on
set number
set cursorline
filetype on
colorscheme onedark
`
my .vimrc file like this

**Comment by simonsmith** [comment]
Are you using iTerm? And vim or neovim?

**Comment by joenil** [comment]
@simonsmith Yes, it's iTerm2 Build 3.0.0, not neovim.

**Comment by simonsmith** [comment]
Try `let g:onedark_termcolors=16` before the `colorscheme` option. The README goes into more detail on the difference between 16 and 256 mode.

**Comment by joenil** [comment]
@simonsmith It became like this, the background is going dark, but also got an incorrect colors.
![image](https://cloud.githubusercontent.com/assets/11400674/16186509/7d168688-36fd-11e6-81ac-2240d892e17f.png)

**Comment by joshdick** [comment]
@joenil What you're now seeing in 16-color mode is happening because you're not using `One Dark.itermcolors` like the README specifies.

**Comment by joenil** [comment]
@joshdick wow~it works! thank you very much, very like this amazing colors!
