### ISSUE TITLE
background color over ssh in HyperTerm

### ISSUE THREAD

**Issue by weslleyaraujo** [joshdick/onedark.vim#41]
#### Local

* VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2016 14:20:57)
* echo $TERM; // xterm-256color

![screen shot 2016-07-19 at 5 22 23 pm](https://cloud.githubusercontent.com/assets/2286385/16955574/6d57e2a2-4dd5-11e6-9c5d-f4ffe92a155a.png)

#### SSH

* VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 24 2015 02:23:23) 
* echo $TERM; // xterm-256color

![screen shot 2016-07-19 at 5 22 25 pm](https://cloud.githubusercontent.com/assets/2286385/16955582/71b95858-4dd5-11e6-8b36-13bb6c058f82.png)

It seems like only the background color is slightly different over `ssh` then in my local vim..
any ideas what might be causing this?

**Comment by joshdick** [comment]
I'm assuming you're SSHing locally/into the same machine where Vim ran locally?

**Comment by weslleyaraujo** [comment]
well, in the second screenshot is vim running over my ssh connection... I might not really understand the question 😅

**Comment by joshdick** [comment]
Are you accessing the same computer in both cases (locally in the first case and by SSHing to itself in the second case?) Or are you SSHing to a different machine that could potentially have different configuration?

**Comment by weslleyaraujo** [comment]
I am SSHing to a different machine 👍

**Comment by joshdick** [comment]
It looks like the remote machine is using 256-color mode even though it's configured to use `termguicolors` if available.

Can you run `vim --version | grep patches` on both machines and paste the output here? Vim needs to be at least at patch 7.4.1799 for your pictured configuration to show the correct colors.

I suspect that your local machine (which is showing correct colors) may have a newer version of Vim than the remote one (which appears to be using 256-color mode.)

**Comment by weslleyaraujo** [comment]
Indeed, it looks like this is the issue:

#### Local
Included patches: 1-1910

#### SSH
Included patches: 1-207, 209-629

I will try updating vim over ssh 👍

**Comment by weslleyaraujo** [comment]
thanks for the support, working properly after upgrade :)

**Comment by joshdick** [comment]
You're welcome, glad to hear it!
