### ISSUE TITLE
nerdtree colors

### ISSUE THREAD

**Issue by zackhsi** [joshdick/onedark.vim#42]
Hey again! Long time no see :)

So I use nerdtree, which colors directories blue and executables red. But not with onedark.

<img width="226" alt="screen shot 2016-07-19 at 7 28 02 pm" src="https://cloud.githubusercontent.com/assets/806101/16973287/5dd28d34-4de7-11e6-9df7-13f1557a0e07.png">

Ideas?

**Comment by simonsmith** [comment]
I've checked and each one can be styled so just a case of adding appropriate colours.

**Comment by joshdick** [comment]
Zack,

The blue directory and red executable colors you mentioned seem arbitrary, since NERDTree seems to rely on the current theme's `Directory` and `Title` highlight groups for coloring, respectively, but I agree that theme could work better with NERDTree. Will discuss this more in #43.
