### ISSUE TITLE
Change VertSplit color

### ISSUE THREAD

**Issue by felixjung** [joshdick/onedark.vim#45]
Hi,

I really like your theme! Great job! One tiny nitpick I have, however, is the way the separator for vertical splits is colored. I find the black a bit too strong. I played around a bit with the colors and found that using `s:cursor_grey` instead of `s:vertsplit` looks much less obtrusive. I've attached a screenshot. Is this something you would be willing to change?

![screen shot 2016-07-31 at 15 49 02](https://cloud.githubusercontent.com/assets/265947/17276907/54a5c48a-5736-11e6-8798-1020437f9104.png)

**Comment by joshdick** [comment]
I originally chose the black color because that's the split color Atom's One Dark theme uses. I tried using VertSplit like you proposed and I'm not sure it's better, though I know it pretty much comes down to personal preference.

I won't decide immediately either way.

**Comment by joshdick** [comment]
After thinking about it for a day, I've decided I'm going to leave the theme as is. The current way is closer to Atom's One Dark theme, and also seems to me to be better at helping to visually distinguish between splits when line numbers are disabled. So, I'm going to close #46. Thanks again for the idea and the PR!

**Comment by felixjung** [comment]
Sure. Thanks for creating such a great port of this beautiful theme!

**Comment by joshdick** [comment]
You're welcome, I'm glad you like it!
