### ISSUE TITLE
is there an atom version of this theme? 

### ISSUE THREAD

**Issue by NullVoxPopuli** [joshdick/onedark.vim#47]
I really like these colors (better than the current atom onedark theme). It would be great to have an atom version. :-)

**Comment by joshdick** [comment]
This theme's colors are meant to mirror the "official" colors from Atom's built-in One Dark theme as closely as possible. I'm not sure if you're referring to the colors themselves or the syntax highlighting rules (which are somewhat unique to both editors), but either way there are currently no plans to backport any aspect of this project to Atom.

**Comment by NullVoxPopuli** [comment]
cool, thanks!
