### ISSUE TITLE
Flow syntax highlight

### ISSUE THREAD

**Issue by isomoar** [joshdick/onedark.vim#52]
First of all I want to say that this theme is great and my favourite, really good work. 👍 
Are you going to support flow syntax? It would be really nice. This is how it looks now: 

![](http://i.imgur.com/oR9OLcz.png)

**Comment by simonsmith** [comment]
You'll need a separate plugin to handle the Flow syntax. I'm using [vim-javascript](https://github.com/pangloss/vim-javascript) which handles it well and didn't need any colour tweaks in my opinion:

![screen shot 2016-08-31 at 14 02 54](https://cloud.githubusercontent.com/assets/360703/18129670/a26393e0-6f83-11e6-930e-bdae9602d326.png)

Once you install that and enable `let g:javascript_plugin_flow = 1` option it should start to highlight correctly. However I did bump into [this issue](https://github.com/pangloss/vim-javascript/issues/612), which might be relevant

**Comment by isomoar** [comment]
@simonsmith I didn't know about that option, thank you so much! 😍  🎉
