### ISSUE TITLE
Move airline theme into this repo

### ISSUE THREAD

**Issue by simonsmith** [joshdick/onedark.vim#53]
What do you think about moving the airline theme into this repository? In the past I've found it very useful to be able to switch to the airline theme without installing another plugin.

Example themes:
* https://github.com/whatyouhide/vim-gotham
* https://github.com/rakr/vim-two-firewatch

I expect it will make maintenance much easier especially if we added a lightline theme.

**Comment by joshdick** [comment]
This has come up before with #16. I was on the fence about this then, but a bug or two has come up since then that has involved conflicting changes between the two repos, so I now think moving the airline theme into this repo makes sense.
