### ISSUE TITLE
Split delimiter line is black 

### ISSUE THREAD

**Issue by rumpelsepp** [joshdick/onedark.vim#54]
The split delimiter line of `|` symbols is black, and thus hardly visible.

**Comment by simonsmith** [comment]
This was raised in #45. That issue should give you some background on why it's black

**Comment by joshdick** [comment]
Interesting, some find it too visible while others find it not visible enough! This is probably an even better sign not to change it. Per #45, I'm not going to change the color for now. Thanks for the report!
