### ISSUE TITLE
tmux with vim highlight color not working

### ISSUE THREAD

**Issue by ryosuke-endo** [joshdick/onedark.vim#58]
hi

I work with vim.

so far, I use terminal.

but I use tmux.

one dark syntax high light is not working.

why?

.vimrc
```
let g:onedark_termcolors=16
```

**screenshot with terminal**

[![https://gyazo.com/24aae7222776162057dbf8c2377dc578](https://i.gyazo.com/24aae7222776162057dbf8c2377dc578.png)](https://gyazo.com/24aae7222776162057dbf8c2377dc578)

**screenshot with tmux**

[![https://gyazo.com/d14104eb81f67abfd3e125bcfce8dca3](https://i.gyazo.com/d14104eb81f67abfd3e125bcfce8dca3.png)](https://gyazo.com/d14104eb81f67abfd3e125bcfce8dca3)

**Comment by ryosuke-endo** [comment]
I solve this problem

**tmux**
```
  % echo $TERM
screen
```

I set up **screen-256color**

sorry!

**Comment by joshdick** [comment]
Glad you figured it out!
