### ISSUE TITLE
incsearch doesn't highlight

### ISSUE THREAD

**Issue by danarnold** [joshdick/onedark.vim#6]
When using onedark, the incremental search results aren't highlighted, making it impossible to use the incsearch feature.

Steps to reproduce:

1. Edit a file with some text in it.
2. `:set incsearch`
3. `/` and start typing something in the file.

**Comment by joshdick** [comment]
Thanks for the report!

**Comment by danarnold** [comment]
No problem, thanks for the scheme & the quick fix. :smile:

**Comment by joshdick** [comment]
You're welcome!
