### ISSUE TITLE
Increase Constrast of Cursor

### ISSUE THREAD

**Issue by rumpelsepp** [joshdick/onedark.vim#60]
The cursor is hardly visible when writing *new* code. Please consider increasing the contrast a bit.

**Comment by simonsmith** [comment]
Do you mean you struggle to see it in Insert mode? I'm not having that difficulty in either Vim or Neovim in iTerm (tmux).

What Vim version and terminal do you use?

**Comment by rumpelsepp** [comment]
Terminal: `termite`
neovim, latest

Yes, I do. The cursor changes its color depending on which snippet it is placed. When I am in insert mode and no character is under my cursor, I can hardly see it. It is grey on grey.

**Comment by joshdick** [comment]
Can you post a screenshot please (with some other code open so I can see the rest of the colors?)

**Comment by rumpelsepp** [comment]
Yes. I am in the subway right now. Will send it tonight.

**Comment by rumpelsepp** [comment]
![screenshot-2016-10-05-00 43 05](https://cloud.githubusercontent.com/assets/1961699/19095221/e1b07cda-8a94-11e6-9349-02817f021b19.png)
![screenshot-2016-10-05-00 43 53](https://cloud.githubusercontent.com/assets/1961699/19095222/e1c4b614-8a94-11e6-9f7c-5e10f392fd0c.png)

**Comment by joshdick** [comment]
The screenshot was helpful; I was able to reproduce this in termite even when X-forwarded to a Mac.

This doesn't have to do with the theme but instead seems to be an idiosyncrasy of termite. Termite appears to be changing the cursor color to the foreground color of whatever character appears underneath it.

One solution I figured out is to not use `list`/invisibles in Vim; if characters with that color never show up in Vim, the cursor won't change to that color.

A much better solution is to set an explicit cursor color in your `~/.config/termite/config`, for example, `cursor = #ABB2C0`. Termite seems to stop dynamically "absorbing" cursor colors if a cursor color is explicitly set in the configuration.

I hope that helps!

**Comment by rumpelsepp** [comment]
Thanks for your answer!

> One solution I figured out is to not use list/invisibles in Vim; if characters with that color never show up in Vim, the cursor won't change to that color.

That's not a solution for me, as I always need to fix whitespace errors when working with other people to avoid silly errors...

> A much better solution is to set an explicit cursor color in your ~/.config/termite/config, for example, cursor = #ABB2C0. Termite seems to stop dynamically "absorbing" cursor colors if a cursor color is explicitly set in the configuration.

That would be the preferable solution. Unfortunately it does not seem to work an my machine the same way. Which version of termite are you using?

**Comment by joshdick** [comment]
I'm using termite v11. Here's my entire termite config:

```
[options]

clickable_url = true
font = DejaVu Sans Mono 9

[colors]

# special
foreground = #ABB2C0
background = #282C34
cursor = #ABB2C0

# black
color0 = #282C34
color8 = #3E4452

# red
color1 = #E26B73
color9 = #C04F43

# green
color2 = #97C475
color10 = #97C475

# yellow
color3 = #E6C176
color11 = #D29B62

# blue
color4 = #5DAEF2
color12 = #5DAEF2

# magenta
color5 = #C775DF
color13 = #C775DF

# cyan
color6 = #51B6C3
color14 = #51B6C3

# white
color7 = #ABB2C0
color15 = #5C6670
```

**Comment by rumpelsepp** [comment]
Thanks! Got it. It seems, that termite did not source the config file properly. I first had to kill all instances... Anyway, I am not very happy with the result as a static cursor color does not ensure that every color *under* the cursor is readable. There are colors that are ok, and there are colors that are hardly visible.

I also tried gnome-terminal, which is also a vte terminal. Surprise, surprise, it behaves the same as termite. Is there some setting, so that I can change the color of the invisibles locally on my machine? That would work for, I guess.

**Comment by joshdick** [comment]
Okay, glad you figured it out.

You can add a line like:

`:hi SpecialKey guifg=#5C6370 ctermfg=59`

after the `colorscheme onedark` line in your Vim configuration.

This way, you can tweak the full (hex) color and/or 256-color settings to your liking
