### ISSUE TITLE
Italics supports in iterm2 and vim

### ISSUE THREAD

**Issue by kepbod** [joshdick/onedark.vim#61]
It seems like only `let g:onedark_terminal_italics=1` before `colorscheme onedark` could not make it become Italics. I also added below gists in `.vimrc` and turn on Iterm2 italics supports using this [gists](https://gist.github.com/kepbod/2ea79ee2ada4c22591dc043c1ed4364c).

```
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"
```

My vim configuration lists [here](https://github.com/kepbod/ivim/blob/master/vimrc_mini#L209).

**Comment by joshdick** [comment]
I'm not exactly sure what you mean; are you saying italics work when configured one way but not some different way?

**Comment by kepbod** [comment]
I meant more configurations require setting to turn on  italics.

**Comment by joshdick** [comment]
I see; this is not a bug in onedark.vim but is instead a terminal and TERMINFO-specific problem. I also use iterm2 and used some of the suggestions [here](https://alexpearce.me/2014/05/italics-in-iterm2-vim-tmux/) to get italics working in iterm2. I needed a custom TERMINFO but didn't need any lines in my `.vimrc` other than `let g:onedark_terminal_italics=1`.

I updated the README to mention this in 9a6a90e.

Thanks for the report!
