### ISSUE TITLE
Italic HTML attribute names

### ISSUE THREAD

**Issue by garand** [joshdick/onedark.vim#66]
Would you consider adding an option for italic HTML attribute names? I tried adding `highlight htmlArg cterm=italic` to my VIMRC but it didn't work.

**Comment by garand** [comment]
I added this to the `onedark.vim` file and it is working properly. Maybe I'll submit a PR later!
<img width="620" alt="screen shot 2016-12-15 at 11 36 23 am" src="https://cloud.githubusercontent.com/assets/82437/21232737/bc92f55a-c2ba-11e6-94e4-ba19f657b47d.png">

**Comment by simonsmith** [comment]
Hey,

Unless it matches the Atom theme I don't think we would add it. Might be something to keep in your own fork.

**Comment by webdesus** [comment]
@garand you can add function s:h inside your VIMRC, and ibid write you own change(call s:h("htmlArg", ...)) or make fork.

**Comment by joshdick** [comment]
@garand Thanks for the suggestion, but I agree with @simonsmith and @webdesus -- this would not match the Atom theme and thus I don't think it should be changed.

**Comment by garand** [comment]
@joshdick Okay, sounds good. 👍 

@webdesus I'm not foo familiar with what you're saying, do you have an example I could look at?

**Comment by webdesus** [comment]
@garand  add this function code in VIMRC
```
function! s:h(group, style)
  if g:onedark_terminal_italics == 0
    if has_key(a:style, "cterm") && a:style["cterm"] == "italic"
      unlet a:style.cterm
    endif
    if has_key(a:style, "gui") && a:style["gui"] == "italic"
      unlet a:style.gui
    endif
  endif
  if g:onedark_termcolors == 16
    let l:ctermfg = (has_key(a:style, "fg") ? a:style.fg.cterm16 : "NONE")
    let l:ctermbg = (has_key(a:style, "bg") ? a:style.bg.cterm16 : "NONE")
  else
    let l:ctermfg = (has_key(a:style, "fg") ? a:style.fg.cterm : "NONE")
    let l:ctermbg = (has_key(a:style, "bg") ? a:style.bg.cterm : "NONE")
  endif
  execute "highlight" a:group
    \ "guifg="   (has_key(a:style, "fg")    ? a:style.fg.gui   : "NONE")
    \ "guibg="   (has_key(a:style, "bg")    ? a:style.bg.gui   : "NONE")
    \ "guisp="   (has_key(a:style, "sp")    ? a:style.sp.gui   : "NONE")
    \ "gui="     (has_key(a:style, "gui")   ? a:style.gui      : "NONE")
    \ "ctermfg=" . l:ctermfg
    \ "ctermbg=" . l:ctermbg
    \ "cterm="   (has_key(a:style, "cterm") ? a:style.cterm    : "NONE")
endfunction

```

Then add what you want. For this problem you should add next code
```
let s:dark_yellow = { "gui": "#D19A66", "cterm": "173", "cterm16": "11" }
call s:h("htmlArg", {"fg": s:dark_yellow, "gui":"italic","cterm": "italic"})

```

**Comment by webdesus** [comment]
Hey @garand now you can easily change some styles [link](https://github.com/joshdick/onedark.vim#how-can-i-customize-onedarkvims-look-without-forking-the-repository)

**Comment by garand** [comment]
@webdesus Great! Thanks. 😄
