### ISSUE TITLE
vim-airline issue: Syntastic Errors not showing up when using onedark colorscheme

### ISSUE THREAD

**Issue by deybhayden** [joshdick/onedark.vim#68]
When I use the onedark airline theme, I don't see the expected `[Syntax: line:xx` in the status line for syntax errors. Below is a minimal vimrc (using Vim 8.0 with packages to install both onedark and syntastic at startup) that shows the issue. Comment out `colorscheme onedark` to default to the current theme and show the syntastic error part of the status line again.

```vim
" onedark
if (has("termguicolors"))
  set termguicolors
endif
colorscheme onedark

" syntastic
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
```

Screenshots are taken while looking at the same file with one syntastic error.

<img width="541" alt="screen shot 2016-12-21 at 5 10 43 pm" src="https://cloud.githubusercontent.com/assets/877908/21409860/572ebb8a-c7a2-11e6-9605-3198882da9c1.png">
<img width="397" alt="screen shot 2016-12-21 at 5 09 55 pm" src="https://cloud.githubusercontent.com/assets/877908/21409861/572ef550-c7a2-11e6-9c31-af71cd69d0c9.png">

Thanks for this scheme, I'm a big fan! Just curious if I'm missing something obvious.

**Comment by joshdick** [comment]
I use plug.vim to load plugins and can't reproduce this with that setup, but this was a plugin loading problem I'd expect the theme and/or syntastic not to load at all, so, stupid question: Is this an artifact of Vim's Location buffer being selected by default when a syntax error is detected? I have to refocus my source code buffer after introducing a syntax error in order for the statusline to show the syntax group as expected.

**Comment by deybhayden** [comment]
Aha, that's it! I had to run `packloadall` at the very top of my .vimrc so that all the runtime paths were updated before setting the colorscheme. Vim packages by default in 8.0 are loaded to the runtime after reading the .vimrc.

<img width="596" alt="screen shot 2016-12-22 at 9 27 31 am" src="https://cloud.githubusercontent.com/assets/877908/21430449/e9cf3f88-c828-11e6-932f-714c35e21528.png">

Is that the right color though? Looks like the default. Regardless, my original issue is a vim package issue.

**Comment by deybhayden** [comment]
Actually had to set a couple airline variables ahead of that `packloadall` to get my powerline font to show up right as well. I think i've got it sorted - thanks for helping me pinpoint that it was just an environment thing.

**Comment by joshdick** [comment]
Glad you figured out it was an environment thing!

Thanks for pointing out the incorrect red color, it was bothering me too! After doing a little digging, I figured out how to set the error and warning colors and have just pushed 825716f8da70d4d9413fa28fbb5d92e2cd6c54d8 to correct them.
