### ISSUE TITLE
Issues with color

### ISSUE THREAD

**Issue by fayimora** [joshdick/onedark.vim#73]
Thanks a lot for this plugin. I can now switch back to vim 😄 

I've just set it up and have been having some odd inconsistencies.

- Colors in lightline (Terminal Vim)
![](https://fayidrop.s3-eu-west-1.amazonaws.com/Screen-Shot-2016-12-27-12-20-24.png)
Mine looks like the above but I don't think this is what it should look like

- Colors in lightline (MacVim)
![](https://fayidrop.s3-eu-west-1.amazonaws.com/Screen-Shot-2016-12-27-12-35-13.png)
I have the same settings in my `.gvimrc` but the default solarised theme doesn't seem to want to be changed from solarised.

- Nerdtree colors 
![](https://fayidrop.s3-eu-west-1.amazonaws.com/Screen-Shot-2016-12-27-12-36-50.png) Yet another color issue I cant figure out. I woul dhave expected it to match https://github.com/joshdick/onedark.vim/commit/ba78df21827bcc7c0ebd875efc37ace2650c55c8

**Comment by fayimora** [comment]
```vim
" .vimrc
let g:onedark_termcolors=16
syntax on
colorscheme onedark
set background=dark
let g:lightline = {
  \ 'colorscheme': 'onedark',
  \ }
let g:airline_theme='onedark'
```

```vim
" .gvimrc
syntax on
set background=dark
colorscheme onedark
let g:lightline = {
  \ 'colorscheme': 'onedark',
  \ }
let g:airline_theme='onedark'
```

**Comment by sijad** [comment]
maybe this is because of true color, [this might works](https://github.com/joshdick/onedark.vim#installation):

``` "Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
"If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
"(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
if (empty($TMUX))
  if (has("nvim"))
    "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
endif
```

**Comment by fayimora** [comment]
@sijad I don't think it is. I tried that and got patches of solarised in the terminal(in nerdtree and lightline)

**Comment by joshdick** [comment]
In MacVim, aside from lightline, do the theme's colors otherwise appear correctly?

In terminal Vim, you've configured `let g:onedark_termcolors=16` which will use your terminal's built-in colors if you aren't using true-color mode like @sijad mentioned. You either need to enable true color mode, or set your terminal to use onedark.vim's terminal colors as described in the README.

**Comment by fayimora** [comment]
I'm quite confused right now. Does this mean i have true color? 

![](https://fayidrop.s3-eu-west-1.amazonaws.com/Screen-Shot-2016-12-28-10-40-02.png)

**Comment by fayimora** [comment]
@joshdick Yeah so far everything else appears properly. I also have my iTerm theme set to the preset you have in the repo.

**Comment by fayimora** [comment]
I seem to have managed to get this working. The only issue now is my vim's background colour in when using tmux is a bit off.

![](https://fayidrop.s3-eu-west-1.amazonaws.com/Screen-Shot-2016-12-28-22-00-57.png)
![](https://fayidrop.s3-eu-west-1.amazonaws.com/Screen-Shot-2016-12-28-22-06-36.png)

I followed the instructions at [tmux-24bit-color.html#usage](https://sunaku.github.io/tmux-24bit-color.html#usage) but that didn't help 😢  Yes I have the tmux block from the README in my vimrc

**Comment by joshdick** [comment]
Okay, it looks like 256 color mode is being used inside tmux.

Inside tmux, if you run `tmux info | grep Tc`, do you see the output `Tc: (flag) true`? Are you using `vim` or `nvim` inside tmux, and if so, which version(s)?

**Comment by fayimora** [comment]
@joshdick 

![](https://fayidrop.s3-eu-west-1.amazonaws.com/Screen-Shot-2016-12-29-02-00-42.png)

![](https://fayidrop.s3-eu-west-1.amazonaws.com/Screen-Shot-2016-12-29-02-00-57.png)

**Comment by fayimora** [comment]
oh and the config looks like this 
```tmux
set -g default-terminal xterm-256color
set-option -ga terminal-overrides ",xterm-256color:Tc"

```

**Comment by joshdick** [comment]
If you're using the snippet @sijad mentioned above, you should remove the first and last lines (the `if (empty($TMUX))` check and corresponding `endif`.)

If that doesn't do the trick, can you post your entire .vimrc somewhere?

**Comment by fayimora** [comment]
@joshdick THANKS! That fixed it. 👍 ⚡️

**Comment by joshdick** [comment]
You're welcome, glad we figured it out!
