### ISSUE TITLE
Not seeing true colors on tmux/nvim

### ISSUE THREAD

**Issue by yosiat** [joshdick/onedark.vim#75]
Hi,

This my environment:

- macOS sierra 10.12.1
- iterm2  3.0.13 - with `xterm-256color` and onedark-256 itermcolor

- tmux 2.3 (with true color, checked with "tmux info | grep Tc"
- nvim 0.1.7

Here is `~/.vimrc` (the part which is related to the colors):
```
set t_Co=256
let g:rehash256 = 1
let g:onedark_termcolors=256

set background=dark
colorscheme onedark
```

and in tmux I see those colors:
<img width="431" alt="screen shot 2017-01-18 at 11 43 28 pm" src="https://cloud.githubusercontent.com/assets/306253/22084237/fe5fb4c2-ddd7-11e6-8187-50405c74b2b8.png">

Outside of tmux it works.

Is this tmux issue? if so what's the specific issue?

**Comment by joshdick** [comment]
Please try the config snippet in step 1 of the README with the outer `if (empty($TMUX))` check removed.

**Comment by simonsmith** [comment]
Possible dupe of #73 #74 #69

**Comment by joshdick** [comment]
(Really, this just amounts to adding ` set termguicolors` to your vim configuration.)

**Comment by yosiat** [comment]
the config snippet don't work at all, but only `set termguicolors` worked great!

Thanks @joshdick
