### ISSUE TITLE
onedark theme for tmux

### ISSUE THREAD

**Issue by odedlaz** [joshdick/onedark.vim#78]
Hey,
I've created a onedark theme, [_tmux-onedark-theme_](https://github.com/odedlaz/tmux-onedark-theme), based on the work you did.
Do you mind adding a comment about it in your readme?

**Comment by simonsmith** [comment]
I was going to mention tmuxline but then [I saw your issue](https://github.com/edkolev/tmuxline.vim/issues/74). Is this a version that works in true color mode?

Out of interest did running tmux from master fix that problem in tmuxline?

**Comment by odedlaz** [comment]
Unfortunately tmuxline doesn't work.
The generated snapshot doesn't resemble one dark at all. Furthermore, you can't control the "widgets" on the status line, which is very useful imo.

This version works in true color mode, and requires support for true color in tmux panes, which was added to the master branch a few months ago (I referenced that in the README).

I've compiled the master branch and it works flawlessly :)

**Comment by joshdick** [comment]
Done. Good idea. Thank you!

**Comment by odedlaz** [comment]
:+1: :smile:
