### ISSUE TITLE
Grey background

### ISSUE THREAD

**Issue by raphaelcosta** [joshdick/onedark.vim#8]
Hi, 

First, congrats for this color scheme!

I am getting a grey background, any idea why?

https://www.dropbox.com/s/f0cefosv3w4lff6/Screenshot%202016-01-14%2017.35.00.png?dl=0

Thanks!

**Comment by joshdick** [comment]
Glad you like the colorscheme!

The colors you see are the correct/expected ones when using the colorscheme in 256-color mode as you've configured it (`let g:onedark_termcolors=256`).

Switching to 16-color mode will use better/proper colors, but only if your terminal is configured with those colors as described at the bottom of the README.

I hope that helps!
