### ISSUE TITLE
nvim ignoring theme on Ubuntu Mate's terminal

### ISSUE THREAD

**Issue by iceblu3710** [joshdick/onedark.vim#82]
- `nvim --version`: NVIM 0.1.7
- `vim --version`: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48) Included patches: 1-1689 Extra patches: 8.0.0056

- Operating system/version: Ubuntu Mate 14.04
- Terminal name/version: MATE Terminal 1.12.1
- `$TERM`: screen-256color

- init.vim
```
set number
set relativenumber
syntax on

if (has("nvim"))
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif

if (has("termguicolors"))
  set termguicolors
endif

let g:airline_theme='onedark'
colorscheme onedark
```

### Actual behaviour
`nvim init.vim` loads a solid blue background with white text. no airline status line.
`texttty`:`nvim init.vim` loads the base theme properly but no airline status line.
`vim init.vim` loads the base theme properly but no airline status line.

### Steps to reproduce using `nvim -u NORC`
`nvim -u NORC init.vim` loads the base theme properly but no airline status line.
`vim -u NORC init.vim` loads with no themes, just default bgcolor and white text.

**Comment by iceblu3710** [comment]
Duplicate of #83, I somehow posted twice cuz I'm insane.

**Comment by joshdick** [comment]
Do you have separate `vim` and `nvim` configuration, or is your `nvim` configuration symlinked similar to the following setup:
```bash
ln -s ~/.vim ~/.config/nvim
ln -s ~/.vimrc ~/.config/nvim/init.vim
```

**Comment by joshdick** [comment]
Also, when you say "base theme" I'm assuming you mean the onedark.vim theme. If so, I don't understand why `nvim -u NORC init.vim` would load the theme properly as you describe; shouldn't it just load `init.vim` for editing, using whatever the default theme is?
