### ISSUE TITLE
nvim has no stylings while vim does

### ISSUE THREAD

**Issue by iceblu3710** [joshdick/onedark.vim#83]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

`MATE Terminal 1.12.1` On Ubuntu Mate 14.04

### Output From `vim --version`

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     -tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
-clientserver    +iconv           +packages        -toolbar
-clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             -perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            -ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      -mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm  
```

### Output From `~/.vimrc`

```
execute pathogen#infect()

set number
set relativenumber
syntax on
filetype plugin indent on

if (has("nvim"))
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1
endif

if (has("termguicolors"))
  set termguicolors
endif

"vim-airline
let g:Powerline_symbols = 'fancy'
let g:airline_theme='onedark'
set laststatus=2

"Nerd Font
set encoding=utf8
set guifont=Droid\ Sans\ Mono\ for\ Powerline\ Plus\ Nerd\ File\ Types\ 11
let g:airline_powerline_fonts = 1

"OneDark Theme
set background=dark
colorscheme onedark
```

### Issue Description

nvim loads with everything blue. but vi works with correct stylings.

![nvim](https://cloud.githubusercontent.com/assets/187394/23096160/7e2eb2b8-f5dc-11e6-809c-2d0341144631.jpg)

**Comment by joshdick** [comment]
Seems like this is a duplicate of #82 which you also filed; if so, can you close #82?

In #82 you said your `$TERM` is `screen-256color`; are you actually running vim/nvim inide an active `screen` session, or directly in MATE Terminal?

**Comment by iceblu3710** [comment]
running directly in MATE Terminal. I do have Byobu with tmux installed but I am not using it currently.

running on a vtty the styling is correct.

**Comment by joshdick** [comment]
Do you have separate `vim` and `nvim` configuration, or is your `nvim` configuration symlinked similar to the following setup:
```bash
ln -s ~/.vim ~/.config/nvim
ln -s ~/.vimrc ~/.config/nvim/init.vim
```

**Comment by iceblu3710** [comment]
Configs are symlinked. Base theme that vim comes with out of the box.

Its odd that it loads vim-airline but not onedark though.

**Comment by joshdick** [comment]
If you run `printf "\x1b[38;2;255;100;0mTRUECOLOR\x1b[0m\n"` in a terminal, does the text appear red? If not, your terminal emulator (MATE Terminal) doesn't support 24-bit color, which is why you're having these problems. I tried this in MATE Terminal 1.8.1 in a new Ubuntu MATE 14.04 VM, since that's the OS you said you were using, and the aforementioned 24-bit color test failed.

If this is indeed the problem, solutions would be to:

* Use a terminal emulator that does support 24-bit color
* Use onedark.vim in 256- or 16-color mode instead of true-color mode

**Comment by iceblu3710** [comment]
Well it seems that NeoVim just doesn't like to share configs with Vim. I made a seperate NeoVim config in ./config/nvim and using plug everything works like it should.

**Comment by simonsmith** [comment]
@iceblu3710 I symlink my vimrc from one location to both `~/.vimrc` and `~/.config/nvim/init.vim` and use an if statement to separate logic:

```
if has('nvim')
  let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 1
endif
```
If it helps, you can [look at my vimrc](https://github.com/simonsmith/dotfiles/blob/master/dots/vimrc)

**Comment by iceblu3710** [comment]
Interestingly your vimrc gives me the same solid blue background with working plugins like airline.

**Comment by iceblu3710** [comment]
Found the issue, having more plugins made it obvious.

NeoVim has difficulty handling multiple Python versions on the host system, plugins give errors about python3 bindings. The VI versions have no such difficulties. I will report on the NeoVim board.

Thanks!
