### ISSUE TITLE
Colors in diff mode are not clear

### ISSUE THREAD

**Issue by weihanglo** [joshdick/onedark.vim#84]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Output From `vim --version`

```
NVIM v0.2.0-44-g80892924
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161204-38938-xif69t/build/config -I/tmp/neovim-20161204-38938-xif69t/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include-I/usr/include -I/tmp/neovim-20161204-38938-xif69t/build/src/nvim/auto -I/tmp/neovim-20161204-38938-xif69t/build/include
Compiled by weihanglo@weihang-mac

Optional features included (+) or not (-): +acl   +iconv    -jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-8089292/share/nvim"
```

### Issue Description

I love vimdiff and use it a lot in my workflow. However, currents colors for diff mode are too subtle for me to distinguish diff lines and words. Could this theme be more friendly for vimdiff user?

### Github Style Diff

<img width="1251" alt="screen shot 2017-02-21 at 09 57 13" src="https://cloud.githubusercontent.com/assets/14314532/23148461/f318dcb6-f820-11e6-89b2-70b630155738.png">

### Atom splif-diff plugin

<img width="1280" alt="screen shot 2017-02-21 at 10 05 18" src="https://cloud.githubusercontent.com/assets/14314532/23148463/f31dd16c-f820-11e6-80af-c5b24cee85e5.png">

### onedark.vim

<img width="1280" alt="screen shot 2017-02-21 at 10 22 57" src="https://cloud.githubusercontent.com/assets/14314532/23148462/f31df5ac-f820-11e6-8623-0ba7344d6b1c.png">

**Comment by joshdick** [comment]
Thanks for filing this issue!

The existing diffmode colors were chosen to preserve existing syntax highlighting (#59), but I agree that they still make changes somewhat hard to see.

Without preserving syntax highlighting, the changes are much more obvious.

Here's some (meta!) changed diff highlighting, showing changes I made to the diff highlighting 😜:

<img width="1070" alt="screen shot 2017-02-20 at 11 47 54 pm" src="https://cloud.githubusercontent.com/assets/424691/23151211/143d86da-f7c7-11e6-90f9-3612f1da97c9.png">

How does that look? If you have suggestions for improvements I'd love to hear them!

**Comment by weihanglo** [comment]
It looks much more better, but the changed words still difficult to tell. A different background color may be suitable IMO.

**Comment by joshdick** [comment]
The black background for changed text sticks out pretty clearly to me; can you suggest specific background and foreground colors that would make sense next to the contrast of the yellow background color?

**Comment by weihanglo** [comment]
Actually, I tried this combination for some rebase works last day. It felt much comfortable for reading than I thought before. Seems that my  worry was not necessary. Thanks Josh!
