### ISSUE TITLE
Airline colors off

### ISSUE THREAD

**Issue by zackhsi** [joshdick/onedark.vim#85]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Output From `vim --version`

```
NVIM v0.2.0-11-gf2c6cc2d
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161130-53424-bpso46/build/config -I/tmp/neovim-20161130-53424-bpso46/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20161130-53424-bpso46/build/src/nvim/auto -I/tmp/neovim-20161130-53424-bpso46/build/include
Compiled by zhsi@Zack-Hsi-MBP.local

Optional features included (+) or not (-): +acl   +iconv    -jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-f2c6cc2/share/nvim"
```

### Issue Description

Airline colors are off. This is 16 bit.

![onedark airline colors](https://cloud.githubusercontent.com/assets/806101/23272274/70a74a2a-f9af-11e6-90d8-27fe9c3b0c4b.png)

**Comment by joshdick** [comment]
The colors are different to show which window is active. Which colors are you expecting?

**Comment by zackhsi** [comment]
Hmm, I misattributed the bug. It was actually to [vim-airline-themes](https://github.com/vim-airline/vim-airline-themes).

I haven't done the bisect yet, but `3e8ecba` from 9/30/2016 is good.

![fixed](https://cloud.githubusercontent.com/assets/806101/23279488/55aa6ad4-f9ca-11e6-8744-eb7ea04cf5d1.png)

**Comment by joshdick** [comment]
To be clear, are you referring to the background color, or the purple text?

**Comment by zackhsi** [comment]
The background color. Sorry for not clarifying.

**Comment by joshdick** [comment]
This is where the bad change happened: https://github.com/joshdick/onedark.vim/commit/92fd37ee12d08427e835f15a2e0e55a201d165a6#diff-83cb2f3915c3c7c4d43e95f77a3f21b7

Just fixed it, will have to submit a separate PR to [vim-airline-themes](https://github.com/vim-airline/vim-airline-themes).

Thanks for the report!

**Comment by zackhsi** [comment]
After removing vim-airline-themes and pulling onedark.vim to `d5cc6e7`:
- airline background on active window is good. same color as rest of pane.
- airline background on inactive window is bad. still the strange beige instead of the normal gray.

**Comment by joshdick** [comment]
Hmm, it looks like this happened because the old airline theme read styling from other highlight groups, which would use existing 16- or 256-color styling depending on how onedark.vim was configured (but didn't let the airline theme be used without also using onedark.vim), while the new airline theme exclusively uses 256-color styling.

I can probably fix this using a mechanism similar to the one used in https://github.com/vim-airline/vim-airline-themes/blob/bcee47632ea4e9ea5120ac39a22d0eca85b2b132/autoload/airline/themes/solarized.vim but can't do it immediately. Stay tuned.

**Comment by zackhsi** [comment]
Thanks. As I have said in the past, you are the best. 🌴

**Comment by joshdick** [comment]
It ended up being easier/taking less time than I thought, let me know if that works!

**Comment by zackhsi** [comment]
Thanks, better. One more fix: https://github.com/joshdick/onedark.vim/pull/86.

**Comment by joshdick** [comment]
I think I did it this time. 🤣

**Comment by zackhsi** [comment]
Great success. Thanks :)

**Comment by joshdick** [comment]
You're welcome! 😄
