### ISSUE TITLE
Rust doc comments aren't highlighted correctly.

### ISSUE THREAD

**Issue by SirDoctors** [joshdick/onedark.vim#87]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

Terminal emulator(s) and their version(s) used, if applicable: gnome-terminal 3.18.3
### Output From `vim --version`

```
NVIM 0.1.7
Build type: Release
Compilation: /usr/lib/ccache/bin/cc -specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe  -g -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/builddir/neovim-0.1.7/build/config -I/builddir/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/builddir/neovim-0.1.7/build/src/nvim/auto -I/builddir/neovim-0.1.7/build/include
Compiled by xbps-builder@build.voidlinux.eu

Optional features included (+) or not (-): +acl   +iconv    -jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

### Issue Description

When editing a rust file, [doc comments /// & //!]
(https://doc.rust-lang.org/book/testing.html#documentation-tests) don't highlight the same as regular comments. I am using [rust-lang/rust.vim](https://github.com/rust-lang/rust.vim/) for rust support.

![broken hightlighting](http://i.imgur.com/4o6K89T.png)

**Comment by joshdick** [comment]
Fixed, thanks for the report!

That particular syntax highlighting uses the `SpecialComment` highlight group, so I changed the color to match normal comments, but left italics turned off so `SpecialComment`s will still contrast with normal `Comment`s when used with other syntax highlighting.

**Comment by SirDoctors** [comment]
phew, you were efficient at fixing that. Thanks!
