### ISSUE TITLE
matching ( ){ } [ ]  not working

### ISSUE THREAD

**Issue by zamaterian** [joshdick/onedark.vim#9]
Hi. 

Thanks for your work. I started using it from neovim in terminal. 

The only thing that I've trouble with is missing highlightning matching parens, square bracket etc. 
If I change the colorscheme to another schema - its starts working again.. 

I have installed the following syntax plugins, it has no effect toggling rainbows_parentheses

Plug 'guns/vim-clojure-highlight', { 'for': 'clojure' }
Plug 'guns/vim-clojure-static', { 'for': 'clojure' }
Plug 'junegunn/rainbow_parentheses.vim'

Cheers

**Comment by joshdick** [comment]
Should be fixed now, thanks for the report!
