### ISSUE TITLE
Improving git commit summary title color

### ISSUE THREAD

**Issue by sbdchd** [joshdick/onedark.vim#95]
Currently, when writing git commit messages, the color for the title portion of the git commit message is red. This conflicts with spellcheck, since spellcheck colors words red and underlines them if there is an error.

So when writing the title of the git commit message, it is difficult to distinguish between misspelled and properly spelled words as the only difference is the underline.

Here is the diff that fixes the issue for me:

```diff
diff --git a/colors/onedark.vim b/colors/onedark.vim
index e1597b7..fa6bfc0 100644
--- a/colors/onedark.vim
+++ b/colors/onedark.vim
@@ -494,6 +494,7 @@ call s:h("gitcommitDiscardedFile", { "fg": s:red })
 call s:h("gitcommitSelectedFile", { "fg": s:green })
 call s:h("gitcommitUnmergedFile", { "fg": s:yellow })
 call s:h("gitcommitFile", {})
+call s:h("gitcommitSummary", {"fg": s:white})
 hi link gitcommitNoBranch gitcommitBranch
 hi link gitcommitUntracked gitcommitComment
 hi link gitcommitDiscarded gitcommitComment
```

Before Change:

<img width="570" alt="screenshot 2017-04-19 18 20 43" src="https://cloud.githubusercontent.com/assets/7340772/25204874/98765984-252d-11e7-81cb-86533947c604.png">

After Change:

<img width="570" alt="screenshot 2017-04-19 18 19 55" src="https://cloud.githubusercontent.com/assets/7340772/25204859/8fc64eac-252d-11e7-9b6a-35c6cad5715c.png">

**Comment by joshdick** [comment]
Fixed. Thanks for the report!
