### ISSUE TITLE
HELP: how to modify certain color for javascript syntax

### ISSUE THREAD

**Issue by samumist** [joshdick/onedark.vim#98]
Thanks for this great theme, really love it.
I've tried to modify your theme for the javascript highlight from this:
![vim](https://cloud.githubusercontent.com/assets/3883086/25853518/a79559e2-34ff-11e7-8efe-5c1db8182dcf.png)

To:
![vscode](https://cloud.githubusercontent.com/assets/3883086/25853537/b05c1ef8-34ff-11e7-8416-923cd049228a.png)

with no success.

I couldn't figure out which highlight group to modify. 

Thanks for your help!

**Comment by simonsmith** [comment]
Hey @samumist 

What syntax are you using for JS? That will determine what control you have over the theme.

In terms of determining what group to target I use this - https://github.com/simonsmith/dotfiles/blob/master/dots/vimrc#L822-L825

It will display the current highlight group under the cursor.

**Comment by samumist** [comment]
Hi @simonsmith , many thanks for your prompt reply.
I use https://github.com/sheerun/vim-polyglot for JS syntax. It's a collection of language pack which I believe have https://github.com/pangloss/vim-javascript for javascript.

And thanks for the code. It's really helpful! I'll try to modify these newly identified highlight groups and report back of my progress.

Thanks again for your help!

**Comment by samumist** [comment]
Hello @simonsmith 
Really appreciate your help. I was able to find and modify the highlight group colors. 

Many thanks!

**Comment by joshdick** [comment]
Just a heads up: If you're not already using it, you can use [this mechanism](https://github.com/joshdick/onedark.vim#customizing-onedarkvims-look-without-forking-the-repository) to override/modify onedark.vim settings directly in your `~/.vimrc` without needing to maintain a customized copy of the repository.

**Comment by samumist** [comment]
That's awesome! Really love this mechanism! 
Many thanks!

**Comment by joshdick** [comment]
You're welcome!

**Comment by samumist** [comment]
Hey @joshdick 
I've encountered some odd behavior with my customisation. I have this code in my `.vimrc`:

```vim
syntax enable
set t_Co=256
set background=dark

" Set up true color
if (has("termguicolors"))
	set termguicolors
endif

"Fonts
let g:onedark_terminal_italics=1
let g:enable_bold_font = 1 " set some code to be bold

" custom color highlight group for onedark theme
if (has("autocmd"))
  " Color definition from Onedark theme
  let s:red = { "gui": "#E06C75", "cterm": "204", "cterm16": "1" }
  let s:blue = { "gui": "#61AFEF", "cterm": "39", "cterm16": "4" }

  autocmd ColorScheme * call onedark#set_highlight("jsVariableDef", { "fg": s:red })
  autocmd ColorScheme * call onedark#set_highlight("jsModuleKeyword", { "fg": s:red })
  autocmd ColorScheme * call onedark#set_highlight("jsFuncArgs", { "fg": s:red })
  autocmd ColorScheme * call onedark#set_highlight("jsFuncBlock", { "fg": s:red })

  autocmd ColorScheme * call onedark#set_highlight("jsFunctionKey", { "fg": s:blue })

endif

colorscheme onedark
```

Here I was trying to set the `jsFunctionKey` to `blue`. I assume when I open a `.js` file, the key would be `blue` with my above settings. 

It's not.

But when I resource the `.vimrc` file with `:source $MYVIMRC` then the key turned blue. 
I'm wondering if I'm missing something in my configuration?

**Comment by samumist** [comment]
I think I've found the culprit. 
This [rainbow_parentheses](https://github.com/kien/rainbow_parentheses.vim) seems in conflict with the settings. When I disabled this plugin, the customised color displayed fine. 

Now I just need to figure out how to solve this conflict.

**Comment by joshdick** [comment]
@samumist I'm not sure how to fix it either, but glad you figured out the cause!

**Comment by samumist** [comment]
I ended up with a fork of the [rainbow_parentheses](https://github.com/junegunn/rainbow_parentheses.vim) which still has the color conflict but I can disable it by default and toggle it on whenever I really need it.
